### ISSUE TITLE
Compile Error MoreLinq/ToDataTable.cs

### ISSUE THREAD

**Issue by MHLab** [morelinq/MoreLINQ#1004]
Line 172 produces a compile error
https://github.com/morelinq/MoreLINQ/blob/d684bf868961261bfd3943861460038864a13ab2/MoreLinq/ToDataTable.cs#L162-L175
should it be considered to be changed to
`return body is MemberExpression { NodeType: ExpressionType.Parameter, Member: var member }`

**Comment by viceroypenguin** [comment]
As evidenced on the latest CI build [here](https://ci.appveyor.com/project/raboof/morelinq/builds/46679969), the project builds just fine with the line as it is. I can also confirm that the current master branch code compiles fine on my machine. The code is correct as written. Please check if you are using a version of Visual Studio that does not support this code syntax.

**Comment by atifaziz** [comment]
`MemberExpression { Expression.NodeType: ExpressionType.Parameter, Member: var member }` is the same as writing `MemberExpression { Expression: { NodeType: ExpressionType.Parameter }, Member: var member }`. The former is a [short-hand that's possible since C# 10](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-10#extended-property-patterns) and the latter works for C# 8 or later. It's testing [the node type of `MemberExpression.Expression`](https://learn.microsoft.com/en-us/dotnet/api/system.linq.expressions.memberexpression.expression), which isn't the same thing as saying `MemberExpression { NodeType: ExpressionType.Parameter, Member: var member }`, which is testing the node type of the `MemberExpression`.

There should be no compilation errors as part of this project unless you downgraded the language version from 11:

https://github.com/morelinq/MoreLINQ/blob/ae9eea5b809e5cb3ef06c6d86de4adc034290922/Directory.Build.props#L3

Otherwise, I'm guessing you've copied the code into another project that's not on C# 10 yet? If so, please make sure you abide by [the license](https://github.com/morelinq/MoreLINQ/blob/v3.4.2/COPYING.txt) terms, especially if it's going to be publicly distributed.
