### ISSUE TITLE
Predicate Builder?

### ISSUE THREAD

**Issue by mac10688** [morelinq/MoreLINQ#115]
Would it be possible to add a predicate builder to this project?

http://www.albahari.com/nutshell/predicatebuilder.aspx

**Comment by atifaziz** [comment]
What's the motivation? It's already part of [LINQKit](http://www.albahari.com/nutshell/linqkit.aspx).

**Comment by mac10688** [comment]
One less dependency. I'm not familiar with LINQkit. I'm assuming it's a third party library to pull down from nuget? It just seems like a good fit for this library to me.

**Comment by atifaziz** [comment]
[LINQKit](http://www.albahari.com/nutshell/linqkit.aspx) already includes & ships `PredicateBuilder` as described on the [original page you provided as a reference](http://www.albahari.com/nutshell/predicatebuilder.aspx) so I don't see a reason to duplicate it over here in MoreLINQ. It also seems to have more to do with query providers that translate LINQ queries to foreign database languages like T-SQL. If your goal is to reduce dependencies for your project, you may want to look into [ILMerge](http://research.microsoft.com/en-us/people/mbarnett/ilmerge.aspx). I don't think predicate builder otherwise fits the goal of MoreLINQ, which is to provide *operators* in the spirit of LINQ and really specifically for LINQ-to-Objects (i.e. in-memory implementation over objects & graphs).
