### ISSUE TITLE
Support dnx451 and dnxcore50 projects

### ISSUE THREAD

**Issue by zolrath** [morelinq/MoreLINQ#144]
Is there anything preventing MoreLINQ from targeting dnxcore50 to allow it to be used on cross platform projects? It would certainly be nice to be able to use MoreLINQ everywhere!

**Comment by atifaziz** [comment]
Have you tried the [MoreLINQ PCL](https://www.nuget.org/packages/MoreLinq.Portable)? Some PCL profiles are readily usable on DNX.

**Comment by zolrath** [comment]
I have! MoreLINQ PCL works on dnx451 but its build target doesn't support dnxcore50 so it's not available on other platforms.

**Comment by atifaziz** [comment]
@zolrath Thanks for that feedback. At this time, I'm not investing further time into dnxcore50, which seems to be in [quite some flux](https://blogs.msdn.microsoft.com/webdev/2016/02/01/an-update-on-asp-net-core-and-net-core/). However, if you or anyone is keeping up with the changes and would like to help keep MoreLINQ in sync then I'm happy to consider PRs. Things like damianh/LibOwin#18 and its upkeep go a long way to help, otherwise I'm afraid this'll have to wait.

**Comment by smzinovyev** [comment]
MoreLinq v1.4.0 (not PCL) works well for dnx451 (Full DNX) apps. I have created a sample console app targeting dnx451. It works. I updated Readme.md file with Program.cs and Project.json of a sample console app that uses MoreLinq v1.4.0.

Will work on dnxcore50 case...

**Comment by atifaziz** [comment]
@smzinovyev Thanks for testing and dropping in with the feedback.

**Comment by atifaziz** [comment]
See #194.
