### ISSUE TITLE
Provide FromValues methods

### ISSUE THREAD

**Issue by fsateler** [morelinq/MoreLINQ#150]
The idea would be to have methods to make it easier to generate sequences from values:

```csharp
public static IEnumerable<T> FromValues<T>(T in1);
public static IEnumerable<T> FromValues<T>(T in1, T in2);
public static IEnumerable<T> FromValues<T>(T in1, T in2, T in3);
public static IEnumerable<T> FromValues<T>(params T[] ins);
```

The result would be yielding the parameters in order.

C# already provides an easy way to create arrays, but those are mutable, so they can be undesirable in certain situations.

**Comment by atifaziz** [comment]
Appreciate forking #122 into this one issue but would be best as two separate issues: one for `FromValues` and another for `FromDelegates`, as the merits of each require separate discussions.

**Comment by fsateler** [comment]
Ack. I have split the `FromDelegates` as issue #151. Could you please reopen this issue? I don't seem to be able to do so since you closed it.

**Comment by atifaziz** [comment]
> C# already provides an easy way to create arrays, but those are mutable, so they can be undesirable in certain situations.

Hmm…it is really worth the trouble?

```c#
var s1 = new[] { 123, 456, 789 }.AsEnumerable();
var s2 = MoreEnumerable.FromValues(123, 456, 789);
```

**Comment by fsateler** [comment]
Unfortunately, AsEnumerable does not touch the passed sequence. It is only
a hint for the compiler

https://github.com/dotnet/corefx/blob/master/src/System.Linq/src/System/Linq/Enumerable.cs

Therefore the sequence is still mutable.

**Comment by atifaziz** [comment]
@fsateler So the value proposition of `FromValues` is to guard against anyone from shooting themselves in the foot by downcasting and getting back the array or mutable container? In other words, you want a `ToEnumerable` (conversion) rather than an `AsEnumerable` (masking)? If that's the case, I would say that it has some potential downsides like all the optimizations built-into some of operators would become useless. In other words, `MoreEnumerable.FromValues(123, 456, 789).Count()` would become expensive. I would say that for an array, you would want to render it read-only via [`Array.AsReadOnly`][Array.AsReadOnly]. This would make it immutable *downstream*, but admittedly not at the source.

[Array.AsReadOnly]: https://msdn.microsoft.com/en-us/library/53kysx7b(v=vs.110).aspx

**Comment by fsateler** [comment]
> So the value proposition of FromValues is to guard against anyone from shooting themselves in the foot by downcasting and getting back the array or mutable container?

That is one value. The second is that the intent of the code is more immediately apparent.

> In other words, you want a ToEnumerable (conversion) rather than an AsEnumerable (masking)? 

Rather than a conversion, a generator. Although one version (`params T[]`) would be equivalent to a `ToEnumerable`.

> In other words, `MoreEnumerable.FromValues(123, 456, 789).Count()` would become expensive. 

For the length of the sequences likely to be generated from such a method, this is is unlikely to be problematic.

**Comment by atifaziz** [comment]
> The second is that the intent of the code is more immediately apparent.

Don't quite see how.

> For the length of the sequences likely to be generated from such a method, this is unlikely to be problematic.

Fair point.

Naming-wise, `MoreEnumerable.FromValues` reads long & clumsy. What do you think about `Seq.Create` or `Seq.Return`?

**Comment by fsateler** [comment]
There is now [an immutable collections package](https://www.nuget.org/packages/System.Collections.Immutable), thus one can now do:

```csharp
new [] { 1, 2, 3 }.ToImmutableArray();
```

Which makes this enhancement request partially obsolete. The only remaining value is a bit of syntactic sugar, but I don't think it is worthwhile to spend the effort.

Closing.
