### ISSUE TITLE
Remove Concat overload

### ISSUE THREAD

**Issue by JamesFaix** [morelinq/MoreLINQ#165]
I would suggest removing this overload of Concat:

`IEnumerable<T> Concat(this T head, IEnumerable<T> tail)`

* This is an extension method on **all** types.  What if my type has a `Concat` method already?  
* As the implementation shows, (`return tail.Prepend(head);`) this is really just a `Prepend` operation on the `tail`.

* For `string`, the `Concat` method group starts getting muddy. (see below)

---

**string.Concat Type 1:**
`string head = "hello";`
`string[] tail = new [] { " ", "world", "!" };`
`var message = head.Concat(tail);`

In this instance, the inferred type of `message` is `IEnumerable<string>` not `string` as implied by a string concatenation method.  But since `String : IEnumerable<char>`, we can also have this kind of `Concat`.

**string.Concat Type2:**
`string head = "hello";`
`char[] tail = new [] { ' ', 'w', 'o', 'r', 'l', 'd', '!' };`
`var message = head.Concat(tail);`

Now the inferred type of `message` is `IEnumerable<char>`, also not a `string`, but closer.

**Comment by atifaziz** [comment]
@JamesFaix Your second example won't compile & should result in an error like:

    error CS0176: Static member `string.Concat<char>(System.Collections.Generic.IEnumerable<char>)' cannot be accessed with an instance reference, qualify it with a type name instead

You'll need to do this:

```c#
var head = "hello";
var tail = new [] { ' ', 'w', 'o', 'r', 'l', 'd', '!' };
var message = head.AsEnumerable().Concat(tail);
```

Consequently, there's less confusion.

> This is an extension method on all types. What if my type has a `Concat` method already?

This is an issue & risk with all extensions method and will be caught out during compilation but at least it won't cause a runtime error. It's not a problem specific with `Concat`. I'm closing this as _wont-fix_ because I think the better solution is a more [general conflict-free approach to the operators](https://github.com/morelinq/MoreLINQ/issues/60#issuecomment-133518416) that was outlined when we had issues with `Zip`.
