### ISSUE TITLE
Slice overload: Slice(int)

### ISSUE THREAD

**Issue by Montago** [morelinq/MoreLINQ#172]
like in Javascript, the default of Slice(int index) should be to cut from the index and the rest of the array... 

the secondary overload should be the Slice(int index, int length)

**Comment by Montago** [comment]
I've made a pull request

**Comment by fsateler** [comment]
What is the problem with just using `Skip` ?

**Comment by atifaziz** [comment]
See [my comment](https://github.com/morelinq/MoreLINQ/pull/173#issuecomment-218586951) in the PR (#173):

> This overload doesn't make sense as it's redundant with `Skip` that's already there in LINQ. Skip is optimised for lists. `Slice(index, count)` solely exists as an optimisation of `Skip` + `Take` for lists.

**Comment by atifaziz** [comment]
@Montago [wrote](https://github.com/morelinq/MoreLINQ/pull/173#issuecomment-218679527):

> In that case there's no need for Slice either, since it's just a wrapper for Skip + Take

When all you have is a *sequence*, then yes, `Slice` has no value and seems and acts like just a convenience wrapper around `Skip` + `Take`. However, when `Slice` sees a sequence whose run-time type is a list then it is optimized to index into the list. The motivation behind `Slice(index, count)` is that you're capturing `Skip` + `Take` as a single intention so that optimizations can be applied depending on the *run-time type*.

Beware that `Slice` can appear buggy with respect to `Skip` & `Take`, and depending on your expectations. That is, while `Skip` will throw if the source list is modified during iteration, `Slice` won't. The correctness of that is another topic that can be debated as a separate issue from this.

**Comment by Montago** [comment]
Thanks for the clarification !
