### ISSUE TITLE
MinBy/MaxBy for IQueryable

### ISSUE THREAD

**Issue by jnyrup** [morelinq/MoreLINQ#180]
As `MinBy` and `MaxBy` are eager, this might be problematic for inputs of type `IQueryable` if the resultset is very large.
As Jon Skeet [mentions](http://stackoverflow.com/questions/914109/how-to-use-linq-to-select-object-with-minimum-or-maximum-property-value#comment50742961_914198):
> You'd normally use an OrderBy and First, and hope that the optimizer at the other end works out what to do :)

**Comment by atifaziz** [comment]
Unless I'm understanding @jskeet, I dont believe he meant to imply that eagerness is what's problematic here. I think he was saying you don't need `MinBy` and `MaxBy` for `IQueryable` because you could use `OrderBy` followed by `First` and if the translation layer or remote system's optimizer (post-projection) is clever enough, it will infer that what you meant to do _semantically_ is the equivalent of `MinBy` and execute the query accordingly. In other words, you're being _declarative_ with `OrderBy` and `First` but the execution doesn't have to be word for word.

**Comment by jnyrup** [comment]
Thanks for the quick and very detailed answer.
My thought was to include something like (if it is possible):

    if(source is IQueryable) return source.OrderBy().First();

This would allow to use `MinBy` more places, which I find nicer to reader than `OrderBy().First()` and `MinBy` would behave "optimally" regardless of whether the enumerable is external or in-memory.

**Comment by atifaziz** [comment]
@jnyrup That won't really help or be very useful because while you'll be able to pass in an `IQueryable<T>`, you'll get back an `IEnumerable<T>` and will have to cast it back to an `IQueryable<T>` in order to continue composing correctly. Otherwise, the silent change in types can cause surprises, e.g. changing a remotely projected query into executing locally part way. Also, we try and avoid method in MoreLINQ that act as trivial wrappers/sugar around other compositions. If you find `MaxBy` more readable than the `OrderBy().First()` chain then I suggest you add the one-liner extension for `IQueryable<T>` locally to your project. It'll be simpler and more correct.
