### ISSUE TITLE
Port for netcore

### ISSUE THREAD

**Issue by Trojaner25** [morelinq/MoreLINQ#194]
Since it references mscorlib it can not be used with dotnet core.

Please make MoreLINQ.Core or something like that :+1: 

Thank you for your awesome work.

**Comment by MiffyLiye** [comment]
I ported one at https://www.nuget.org/packages/MoreLinq.Core/
And here is the pull request at https://github.com/morelinq/MoreLINQ/pull/195

**Comment by atifaziz** [comment]
@MiffyLiye So following on from [your comment](https://github.com/morelinq/MoreLINQ/pull/195#issuecomment-247547797) in #195:

> OK. When we have the plan of actions, I can create a new PR.

Here's an initial plan just off the top of my head:

- Retire the `MoreLinq.Portable` project and its test project
- The `MoreLinq` project should target .NET Framework 3.5 and .NET Standard 1.x ([trimmed](https://docs.microsoft.com/en-us/dotnet/articles/core/deploying/reducing-dependencies)) via one `project.json`
- Migrate [`<metadata>` in `morelinq.nuspec`](https://github.com/morelinq/MoreLINQ/blob/14d65bfde6c5a97a68ac42d505f62bfc94d327cf/pkg/morelinq.nuspec#L4-L17) to corresponding areas of `project.json` to the extent that `morelinq.nuspec` can be done away with.
- `MoreLinq.Test` project should test for the frameworks it targets.
- Optionally enable development on non-Windows platforms using VS Code by providing Bash scripts for building and packing. I say optional because this can be done as a separate after an initial migration.

The topic of `.csproj` versus `.xproj` is debatable depending on the pros and cons but based on experience with some other projects, seems like the command-line tooling is in a bit better shape than VS ones.

Let me know if you're willing to go the distance on this or it's turned out to be more than you're willing to bite at the moment.

**Comment by MiffyLiye** [comment]
@atifaziz Most actions look fine.
The only problem may be the ```MoreLinq.Test```, because it depends on ```NUnit 2.x``` which does not support .NET Core. 
We may need to upgrade NUnit  to 3.x and migrate all affected tests (at least 204 cases) before they can run on all target platforms. 

I think upgrading UNnit and tests needs to be done as a separate task before or after the migration.

**Comment by MiffyLiye** [comment]
Mostly done. Changes are
* Updated the ```MoreLinq``` subproject targeting .NET Framework 3.5, PCL, and .NET Standard Library
* Migrated metadata from nuspec to project.json
* Updated ```MoreLinq.Test``` subproject running on .NET 4.0 and .NET 4.0 Client with NUnit 2.6.4
* Removed other subprojects
* Added ```build.ps1```, ```test.ps1```, and ```pack.ps1```. (Developers using other test runners may not need ```.\tools\nuget.exe``` (from https://dist.nuget.org/win-x86-commandline/latest/nuget.exe) and ```test.ps1```.)
* Added ```appveyor.yml``` that will build, test, and pack after each push. (See console log and artefacts on https://ci.appveyor.com/project/MiffyLiye/morelinq)

I will adjust the commits and create a PR later.

**Comment by atifaziz** [comment]
> Additionally, I will setup a CI (with AppVeyor) to run tests and build packages.

These should be scoped out as separate issues.

**Comment by atifaziz** [comment]
[2.0 beta 5](https://www.nuget.org/packages/morelinq/2.0.0-beta05) has been pushed out, which targets .NET Standard 1.6 & therefore .NET Core. Testing & [issue reports](https://github.com/morelinq/MoreLINQ/issues/new) would be welcome.

**Comment by MiffyLiye** [comment]
I also unlisted all [MoreLinq.Core](https://www.nuget.org/packages/MoreLinq.Core/) packages.

**Comment by atifaziz** [comment]
@MiffyLiye Appreciate you remembering and following through on that.
