### ISSUE TITLE
Request - install c# files in .MoreLinq, not MoreLinq folder

### ISSUE THREAD

**Issue by SurajGupta** [morelinq/MoreLINQ#221]
Hello - I'd like to request that the C# nuget packages drop files into a ".MoreLinq" and not a "MoreLinq" folder.  As-is, it's difficult to quickly distinguish MoreLinq from folders containing my own code.  I've seen other projects use the period-suffix to indicate that the folder contains code that was not written by the consumer.  It also sorts nicely, and all of the folders with a period-suffix will appear at the top of the project, making it very easy ignore those folders and navigate between non-period-suffixed folders, which I believe is the majority use case.

**Comment by atifaziz** [comment]
I'm guessing you're talking about the source packages, like [`MoreLinq.Source.MoreEnumerable`](https://www.nuget.org/packages/MoreLinq.Source.MoreEnumerable/)?

>  I've seen other projects use the period-suffix

Care to quote which ones?

If anything, I believe the convention has generally been to put sources under `App_Packages` (e.g. see [`TaskHelpers.Sources`](https://www.nuget.org/packages/TaskHelpers.Sources/) and [`Owin.Extensions.Sources`](https://www.nuget.org/packages/Owin.Extensions.Sources/)) and that probably gives you the same result (separation from your code). So that's probably the fix needed here.

**Comment by SurajGupta** [comment]
Thanks for the quick reply!

Yes, I'm talking about the source packages.  We call them "recipes" at my company, which is a term I've come to like.

re: other projects; I misspoke.  The convention was introduced by a dev I work with and I had thought he had borrowed it from other projects.  The nuget packages that I regularly use that use this convention are from devs I work with.

I'm not a fan of the "App_Packages" approaches.  I don't think it's a stated convention? and if it is I don't take it for granted that it's a good convention just because Microsoft is using it (remember Microsoft's "Framework Design Guidelines"? =)

1. We are often installing these packages in DLL projects, and not "apps"

2. It's still a folder that looks like any other folder that a developer would create for their own code.  So you can have a tree that looks like this, which "mixes-in" code that is not yours with code that is.

/Addition
/App_Packages
/Whatever

with a period-prefix those folders are stacked at the top and you can clearly differentiate stuff that is yours from stuff that isn't

3. There's no great way to exclude the files in those folders from search.  With a period-prefix, some search tools can be configured to treat the folder as hidden (like UNIX does) and you can ignore hidden folders when searching.

Anyways, food for thought.

**Comment by SurajGupta** [comment]
Also, it's the least amount of change from what you're doing now, so it won't catch current users by surprise. =)

**Comment by atifaziz** [comment]
>  I don't think it's a stated convention? 

Not written in stone but [more or less followed as a _convention_ if you look around](https://www.google.co.uk/search?q=nuget+App_Packages+convention). I'm not a fan of `App_Packages` as a name either (assuming it was christened so by ASP.NET folk taking inspiration from `App_Code`, `App_Data`, `App_Start` etc.) but it is what it is and dot-prefix seems more arbitrary and very specific to your case.

> We are often installing these packages in DLL projects, and not "apps"

App is just in the name but doesn't imply an application. Might be bothersome to look at but has no technical implications otherwise.

**Comment by SurajGupta** [comment]
Thanks for considering.  I disagree that the dot prefix is more arbitrary:  1. I've stated a few good/real day-to-day advantages to that convention. 2. the only advantage to "App_Packages" that I'm hearing is that it is a convention in the ASP.net world, but not really across .net  3. we're already doing something that's sub-optimal ("MoreLinq" folder); it's neither App_Packages, nor does it get out of your way.

anyways, food for thought.  I'll close out.
