### ISSUE TITLE
Mark sources to be ignored by code analysis tools when embedding

### ISSUE THREAD

**Issue by SurajGupta** [morelinq/MoreLINQ#222]
When the source packages are installed, those cs files should be excluded from Stylecop and CodeAnalysis (because consumer will have their own rules/conventions which MoreLinq will not comply with).

Unfortunately there are various versions of Stylecop and CodeAnalysis.  Fortunately, all the versions I've used respect the following header and will ignore the file:

    // <auto-generated>
    // </auto-generated>

Could we add this to the top of all of the cs files in the source packages?

**Comment by SurajGupta** [comment]
note that the user can just add this to the installed file, but it will get wiped-up when they upgrade to a newer version of the nuget package and they will have to remember to re-apply that header.

**Comment by atifaziz** [comment]
> Could we add this to the top of all of the cs files in the source packages?

Not at this stage because it would create a lot of maintenance that only helps a very specific scenario. If you're up to the task, I _may_ be willing to consider a PR that adds a _footer_ along the lines of:

```c#
// <auto-generated>
// This is NOT AUTO-GENERATED but this comment exists solely to make
// StyleCop and Microsoft.CodeAnalysis ignore this file for source-
// embedding scenarios.
// See https://github.com/morelinq/MoreLINQ/issues/222 for more.
// </auto-generated>
```

You'd then have to version, update with release notes & test all the [source packages](https://github.com/morelinq/srcpkg).

Bear in mind that those source packages are lagging & I'm not planning to update them or publish new ones unless there's a real burning case/need. In fact, I've just [moved them out to a separate repo](https://github.com/morelinq/MoreLINQ/issues/223). The main reason is that maintaining source code compatibility through various C# syntax versions is impractical. I'd like the project's code base to be able to benefit from the latest versions, which is doable if the delivery is the assembly. Source packages then would only be good for those people who are on at least the same version of C# and expecting that of everyone would not only be a long shot but also unfair. Otherwise MoreLINQ would have to remain on some baseline C# version for a very long time just for the embedding scenario and that would just be a drag. Given this and #221, have you considered just using `MoreLinq.dll` and merging it using [ILMerge](https://www.microsoft.com/en-gb/download/details.aspx?id=17630)? Seems to me it would take care of all the trouble you're running into.

**Comment by SurajGupta** [comment]
Thanks for considering.  I'll pass on that PR and just add the auto-generated snippet myself.  I believe it has to be at the top of the file to indicate to CA and Stylecop that the file should be ignored.

Yes, have considered ILMerge but we currently don't support that in our build pipeline, and I believe that .net core has (or is going to) add this as a first-class citizen of the build, specified in the project json.  So I think we'll get it for free when we migrate to .NET core.

I totally respect the concerns you raised.  Being an open-source project you have to think about a broad audience.
