### ISSUE TITLE
Remove zero-arg ToDelimitedString overload

### ISSUE THREAD

**Issue by atifaziz** [morelinq/MoreLINQ#229]
The utility of `ToDelimitedString` overloads accepting zero arguments and using the list separator from the current culture is of very marginal utility and should be considered as a strong candidate for removal in the next major version/release as a breaking change. If so, then the [next release](https://github.com/morelinq/MoreLINQ/milestone/1) should mark those methods as being obsolete.

Should `null` then be allowed as a delimiter to keep consistency with [`String.Join`](https://msdn.microsoft.com/en-us/library/dd992421(v=vs.110).aspx) that does, and treats `null` effectively as an empty string?

This issue has been forked from #116.

**Comment by fsateler** [comment]
> The utility of `ToDelimitedString` overloads accepting zero arguments and using the list separator from the current culture is of very marginal utility and should be considered as a strong candidate for removal in the next major version/release as a breaking change.

Agreed.

> If so, then the next release should mark those methods as being obsolete.

Also agreed

> Should null them be allowed as a delimiter to keep consistency with String.Join that does and treats as effectively an empty string?

I don't think so. If you want empty string, pass an empty string. Moreover, making a parameter nullable is a non-breaking change (and thus doable in a 3.x release), while making a parameter non-nullable is a breaking change (and thus requiring a 4.0 release).

**Comment by atifaziz** [comment]
> If you want empty string, pass an empty string.

Fair enough.

> making a parameter nullable is a non-breaking change (and thus doable in a 3.x release), while making a parameter non-nullable is a breaking change (and thus requiring a 4.0 release).

I tried re-reading this a couple of time but can't make sense of it. How did you get from 3.x to 4.0?

**Comment by atifaziz** [comment]
Right so if the zero-arg `ToDelimitedString` overload is dropped then that's a breaking change and is currently slated for [the next major version](https://github.com/morelinq/MoreLINQ/milestone/2). At the same time, one has to review what allowing `null` for the delimiter means. Changing its meaning to be the same as an empty string, to match `String.Join`, or disallowing it completely can be made in the same major version as it would also be a breaking change, no? That doesn't have to wait for a 4.0?

**Comment by fsateler** [comment]
> Changing its meaning to be the same as an empty string, to match String.Join, or disallowing it completely can be made in the same major version as it would also be a breaking change, no? That doesn't have to wait for a 4.0?

Right, a choice has to be made at the same time, and doesn't require bumping to 4.0. However, should we want to change the behavior *after* the 3.0 release, then we might have a problem:

| Behavior on 3.0 | Behavior on next release | Is a breaking change? |
| --- | --- | ---|
| Throw an exception |  Same as empty string | No | 
| Same as empty string | Throw an exception | Yes |

I'm sorry I was unclear the first time around. I now see my initial comment could be read as claiming that making more than one breaking change required bumping the version multiple times, which is of course nonsense.

**Comment by atifaziz** [comment]
So, yes, I would make both changes in 3.0: this issue _and_ disallowing `null` (which should be tracked as a new and separate issue).

**Comment by jamesmanning** [comment]
@atifaziz just got the obsolete warning today about the zero-arg overload and as a user of morelinq for ages now, I have to disagree.  IMHO, morelinq is great about making linq constructs **more** usable, and removing the overload that I call most of the time makes it significantly less usable for me.  

A lot of my usage of morelinq includes using it in LINQPad where I often need a collection as a string for display doing ad-hoc queries and .ToDelimitedString() is **perfect** for that.  Just doing a grep on my current *.linq files on disk, there are 50 usages of ToDelimitedString and 34 of the 50 are using the no-argument overload.

Please don't make these breaking changes.  AFAICT it's very little additional code for, as a user, *significant* utility. 😄 Could change the 1-arg to string delimiter = null and keep the `delimiter = delimiter ?? CultureInfo.CurrentCulture.TextInfo.ListSeparator` but I'm guessing there are reasons that's probably not viable.

I'm all for getting rid of parts of a library/api that aren't being used, but if that's the impression for the zero-arg overload, let me please beg of you to consider keeping it.  The small (AFAICT) marginal benefit of removing it (and forcing a non-null delimiter) is exceeded (IMHO) by the marginal cost of making a significantly less usable ToDelimitedString extension for your users.

In case I'm missing something, are there non-obvious benefits to removing it?  If it's because it's culture-specific would switching to InvariantCulture for the list separator lookup be acceptable?  It seems to be the only place using CultureInfo in library code (ignoring codegen and test code), but AFAICT that doesn't get any runtime benefits since it's in mscorlib and it's part of the .Net Standard at least since 1.0

Thanks! 😄

**Comment by atifaziz** [comment]
@jamesmanning I trust you've read the background in #116 that lead to the issue here?

> morelinq is great about making linq constructs more usable

This was never the library's goal and contributions have been rejected that are mere trivial operations (e.g. #203).

As for usability, we are talking about just one parameter here so the argument of how much hassle this causes works both ways, no? :smile:

Let me ask, is your issue future usability of not having to type `","` as a delimiter each time or is it updating the current 50 or so files you have on disk using the obsolete overload.

> Could change the 1-arg to string `delimiter = null`

That would still be a breaking change, though binary, not source.

**Comment by jamesmanning** [comment]
@atifaziz I did read #116 and honestly, thought that your defense of ToDelimitedString near the end, especially accepting null like BCL does for things like IFormatProvider, seemed to indicate that you were similarly on board with its usefulness.  I honestly thought that providing an external-user plead that aligned with your thoughts in that comment would be sufficient to keep it... or, at least, I hoped 😄 

Since the root argument in #116 seemed to be about 1) disallowing null and 2) default delimiter not being 'obvious to the casual reader', then, while still a breaking change (as you noted), you could disallow null *and* cover the 'obvious to the casual observer' cases with string delimiter = "," AFAICT

- works the same in all cultures
- default delimiter now obvious to casual observer as its in the interface now
- still supports the 'disallow null as delimiter' goal since we can still check for and throw if an explicit null delimiter is passed
- supports the existing no-argument calls across the ecosystem (including mine 😄 )

Does this seem like a reasonable compromise?

**Comment by atifaziz** [comment]
@jamesmanning Thanks for bringing up all those suggestions and I'll get back to you on those. Meanwhile, you didn't answer my following question:

> Let me ask, is your issue future usability of not having to type `","` as a delimiter each time or is it updating the current 50 or so files you have on disk using the obsolete overload?

**Comment by jamesmanning** [comment]
@atifaziz it's both - sure, updating the existing places (not just my .linq files, lots of C# as well, I just didn't go grep for examples from there), but a lot of my future usage is affected as well since I would plan to keep using the method as long as it's around. 😄
