### ISSUE TITLE
Continuous build for non-Windows platforms

### ISSUE THREAD

**Issue by atifaziz** [morelinq/MoreLINQ#231]

**Comment by fsateler** [comment]
I finally found some time to look into this. Installing dotnet core in my debian machine proved hard (binaries are only good for debian stable, not debian unstable, which is what I use). Therefore I went the easy way and installed the [docker image](https://hub.docker.com/r/microsoft/dotnet/).

1. The dotnet runtime as shipped in the latest image appears to not support `netcoreapp1.0`, but rather `netcoreapp1.1`. Therefore the test project fails to build. I will try now with the 1.0.3 image, but this suggests that maintaining the required versions will not be trivial. Why doesn't the 1.1 runtime satisfy `netcoreapp1.0`? Is this something that should be reported upstream?
2. Running `dotnet build` tries to build all possible configurations, which include the full framework and portable. The first is easily fixed by installing the [official xamarin mono runtime](http://www.mono-project.com/docs/getting-started/install/linux/) (note to self, one needs to enable the gdiplus repository too), but the portable runtime appears to be proprietary and thus not freely available. I don't think extracting the relevant dlls from a windows installer is reasonable to perform during CI, so we probably will need to disable Portable.Net during linux builds.

Sorry I've been slow on this, I hope I can make more progress soonish.

**Comment by fsateler** [comment]
Doh, as I re-read the install page I noticed there is a `referenceassemblies-pcl` package, which should fix the Portable.Net problem.

**Comment by atifaziz** [comment]
> Why doesn't the 1.1 runtime satisfy `netcoreapp1.0`?

From what I understand, they are side-by-side installations that don't interfere with each other anymore:

>  .NET Core is entirely side-by-side, with each installation completely isolated from other installations. You can now be even more flexible in how you deploy systems to machines, and be reassured that introducing another version of .NET Core won't break your other applications. Flexibility is the name of the game here.
>
> Source: [Side by side installation](https://github.com/dotnet/features/blob/6f7bd19b65bc16c4d89a4e26768f3664b3489f68/features/netcore/side-by-side.md)

So you'll need to work with the image for 1.0.

**Comment by fsateler** [comment]
> From what I understand, they are side-by-side installations that don't interfere with each other anymore

OK, I see. I wonder how one is intended to manage the `dotnet` tool itself though.

**Comment by atifaziz** [comment]
The tooling, like `dotnet`, is still in preview so I'm guessing the exact details on the servicing story will be revealed with the release.

P.S. Apparently, [`dotnet` ships with its own private instance of .NET Core](https://twitter.com/citizenmatt/status/747874853135466496).
