### ISSUE TITLE
Safe function

### ISSUE THREAD

**Issue by leandromoh** [morelinq/MoreLINQ#256]
It basically return the self enumerable if its not null ortherwise an empty enumerable. 
The propose of this method is improve readability. 

As Example of usage, we replace this

```
public IEnumerable<T> DoSomething<T>(IEnumerable<T> source)
{
   if (source != null)
   {
      return source
               .Where(foo)
               .Select(bar);
   }

   return Enumerable.Empty<T>();
}
```

for this

```
public IEnumerable<T> DoSomething<T>(IEnumerable<T> source)
{
      return source
               .Safe()
               .Where(foo)
               .Select(bar);
}
```

My draft:

```
public static IEnumerable<T> Safe<T>(this IEnumerable<T> source)
{
      return source ?? Enumerable.Empty<T>();
}
```

**Comment by atifaziz** [comment]
I'm not in favour of this. It doesn't make the code _safer_. If anything, it's _masking_ a null reference with a substitute (empty sequence) so such a method should be called `MaskNull` or something along those lines. Naming aside, I would say that `DoSomething` should be throwing an `ArgumentNullException` instead of permitting a null reference. Now my opinion aside, If someone wants to permit it nonetheless because it's more readable to them then they can have `Safe` in their own app/lib code. There's no value in having such a trivial one-liner expression as part of MoreLINQ.

---
:warning: Subjective material follows… 

If you want to make the following readable:

```c#
public IEnumerable<T> DoSomething<T>(IEnumerable<T> source)
{
   if (source != null)
   {
      return source
               .Where(foo)
               .Select(bar);
   }

   return Enumerable.Empty<T>();
}
```

write it as simply:

```c#
public IEnumerable<T> DoSomething<T>(IEnumerable<T> source) =>
    source == null ? Enumerable.Empty<T>() :
    source.Where(foo).Select(bar);
```
