### ISSUE TITLE
Foreach overload with different action's for last iterations

### ISSUE THREAD

**Issue by leandromoh** [morelinq/MoreLINQ#263]
I needed it this week and searching on web discovery it is a common issue (i saw almost 10 asks on stackoverflow and others sites: [1](http://stackoverflow.com/questions/7476174/foreach-loop-determine-which-is-the-last-iteration-of-the-loop), [2](http://stackoverflow.com/questions/1068110/identifying-last-loop-when-using-for-each), [3](http://stackoverflow.com/questions/6199465/checking-for-the-last-element-in-a-foreach), [4](http://stackoverflow.com/questions/4717120/c-sharp-how-to-get-last-time-in-foreach-statement), [5](https://forums.asp.net/t/1227443.aspx?Check+if+last+iteration+in+foreach), [6](https://bytes.com/topic/c-sharp/answers/777145-last-row-foreach-loop), etc )

so my propose is to create a new method, maybe call it `ForeachLast`.

- `void ForEach<T>(this IEnumerable<T> source, Action<T> defaultFunc, params Action<T>[] lastsFuncs)`
- `void ForEach<T>(this IEnumerable<T> source, Action<T, int> defaultFunc, params Action<T, int>[] lastsFuncs)`

so we can do something like:

```c#
Enumerable.Range(1, 10).ForEach(
	i => Console.Write(i + " "),
	i => Console.Write($"\nlast: {i}"));
```
and get the following output:

```
1 2 3 4 5 6 7 8 9
last: 10
```

since `lastsFuncs `parameter uses `params` we can also do:

```c#
Enumerable.Range(1, 10).ForEach(
	i => Console.Write(i + " "),
	i => Console.Write($"\nthird to last: {i}"),
	i => Console.Write($"\nsecond to last: {i}"),
	i => Console.Write($"\nlast: {i}"));
```

and get

```
1 2 3 4 5 6 7
third to last: 8
second to last: 9
last: 10

```

Here is my draft:

```c#
public static void ForEachLast<T>(this IEnumerable<T> source, Action<T> defaultAction, params Action<T>[] actions)
{
    if (source == null) throw new ArgumentNullException(nameof(source));
    if (defaultAction == null) throw new ArgumentNullException(nameof(defaultAction));

    actions.ForEach((x, i) => {
        if (x == null)
            throw new ArgumentNullException($"{i+1}th last function is null");
    });

    var funcs = actions.Select(x => new Action<T, int>((y, i) => x(y))).ToArray();
    source.ForEachLast((x, i) => defaultAction(x), funcs);
}

public static void ForEachLast<T>(this IEnumerable<T> source, Action<T, int> defaultAction, params Action<T, int>[] actions)
{
    if (source == null) throw new ArgumentNullException(nameof(source));
    if (defaultAction == null) throw new ArgumentNullException(nameof(defaultAction));

    actions.ForEach((x, i) => {
        if (x == null)
            throw new ArgumentNullException($"{i+1}th last function is null");
    });
    
    var col = source as ICollection<T>;
    if (col != null)
    {
        ForEachLastCollectionImpl(col, defaultAction, actions);
    }
    else
    {
        ForEachLastImpl(source, defaultAction, actions);
    }
}

private static void ForEachLastCollectionImpl<T>(ICollection<T> source, Action<T, int> defaultAction, params Action<T, int>[] actions)
{
    var count = actions.Length;
    var len = source.Count - actions.Length;
    var index = 0;

    using(var e = source.GetEnumerator())
    {
        e.MoveNext();

        for (int i = 0; i < len; i++, e.MoveNext())
        {
            defaultAction(e.Current, index++);
        }
        
        for (int i = Math.Abs(count - (source.Count - index)); i < count; i++, e.MoveNext())
        {
            actions[i](e.Current, index++);
        }

    }

}

private static void ForEachLastImpl<T>(IEnumerable<T> source, Action<T, int> defaultAction, params Action<T, int>[] actions)
{
    var count = actions.Length;
    var queue = new Queue<T>(count);
    var index = 0;

    foreach (var item in source)
    {
        if (queue.Count < count)
        {
            queue.Enqueue(item);
            continue;
        }

        defaultAction(queue.Dequeue(), index++);
        queue.Enqueue(item);
    }

    for (int i = Math.Abs(count - queue.Count); i < count; i++)
    {
        actions[i](queue.Dequeue(), index++);
    }
} 
```

**Comment by atifaziz** [comment]
Putting `params` case aside, do you know [`TagFirstLast`][TagFirstLast]? It can handle your first example of:

```c#
Enumerable.Range(1, 10).ForEach(
	i => Console.Write(i + " "),
	i => Console.Write($"\nlast: {i}"));
```

as follows:

```c#
Enumerable.Range(1, 10)
          .TagFirstLast((x, _, last) => last ? $"\nlast: {x}" : x + " ")
          .ForEach(s => Console.Write(s));
```

Since most of the questions your quoted were concerned with only the last element, I suggest we keep this simple and close the issue. That said, the other (`params`) case of dealing with _X_ last items can be done with a combination of existing operators (`Windowed` to create a scrolling windows over _X_ elements and then predicating on a window being the last or not):

```c#
Enumerable.Range(1, 10)
          .Windowed(3)
          .TagFirstLast((w, _, last) => last
                                      ? w.Zip(new[] { "third to ", "second to ", null }, (n, t) => $"\n{t}last: {n}")
                                         .ToDelimitedString(string.Empty)
                                      : w.First() + " ")
          .ForEach(s => Console.Write(s));

// prints:
// 1 2 3 4 5 6 7
// third to last: 8
// second to last: 9
// last: 10
```

I'll admit that it doesn't read pretty but is it common enough to warrant addition of a new operator? The downside of adding a `ForEachLast` is that it's really limiting. It subsumes what you want to do with the last items is just some side-effect. Using `Windowed` with `TagFirstLast`, you can continue to combine in more interesting ways. You don't have to terminate with a `ForEach`.


[TagFirstLast]: https://morelinq.github.io/2.0/ref/api/html/M_MoreLinq_MoreEnumerable_TagFirstLast__2.htm

**Comment by leandromoh** [comment]
> do you know TagFirstLast? It can handle your first example of:

No, I didn't know neither `TagFirstLast` nor `Windowed`. And I must say that these names aren't suggestives for me. 

I think cool my original examples already can be handle with methods that already exists in MoreLinq, but I also think that, as your examples show, it isn't much clear and it's of course non-trivial to write that.

So I still think valid the idea of a new operator. We have methods with trivial code like `TakeEvery`, `Index`, `Consume`, `ToHashSet`. So why don't have one, straight and clear for this non-trivial, too?

How would you handle the following code that `ForEachLast` does, using MoreLinq methods?

```
static void Foo<T>(T obj) { ... }
       bool Bar(int obj) { ... }
static void Dae(int obj) { ... }

Enumerable.Range(1, 10).ForEachLast(
   Foo, 
   x => obj.Bar(x),  
   Dae);
```

**Comment by leandromoh** [comment]
Even putting `params` case aside, MoreLinq's correspondent is a lot more verbose for a trivial task:

```
Enumerable.Range(1, 10).ForEachLast(x => list.Add(x), x => Console.Write(x));
```

Become:

```
Enumerable.Range(1, 10)
        .TagFirstLast((val, _, isLast) => new { isLast, val })
        .ForEach(a =>
        {
            if (a.isLast)
                Console.Write(a.val);
            else
                list.Add(a.val);
        });
```

**Comment by leandromoh** [comment]
@atifaziz ??

**Comment by atifaziz** [comment]
As [I already pointed out earlier](https://github.com/morelinq/MoreLINQ/issues/263#issuecomment-287583801), the principal problem I have with this is that it combines two things into one:

1. Have separate projections/results for tail elements
2. Terminate with a side-effect

It's an issue of API design. We already have 2, which is `ForEach`, so what this should be doing is just 1 because that is more general.

As for your following challenge:

```c#
static void Foo<T>(T obj) { ... }
       bool Bar(int obj) { ... }
static void Dae(int obj) { ... }

Enumerable.Range(1, 10).ForEachLast(
   Foo, 
   x => obj.Bar(x),  
   Dae);
```

Here's how you can do it today:

```c#
Action<int>[] bardae = { (n => Bar(n)), Dae };
Action<int> foo = Foo;

Enumerable.Range(1, 10)
    .Windowed(2)
    .TagFirstLast((w, _, last)
        => last
            ? w.EquiZip(bardae, (x, a) => (X: x, Do: a))
            : new[] { (X: w.First(), Do: foo) })
    .SelectMany(xas => xas)
    .ForEach(xa => xa.Do(xa.X));
```

More important than demonstrating how it can be done with existing operators, what I was to show is that even in this instance, the `ForEach` isn't the fancy part. You project actions (that vary for the last two) out of the range of numbers. Then if you want to apply those actions/side-effects, you simply do that with a `ForEach`.

**Comment by atifaziz** [comment]
@leandromoh In case I wasn't being clear enough, I thought I'd go ahead and demonstrate more concretely how the idea you are proposing here can be applied more generally as _projections with exceptions_, rather than tying it to `ForEach` only. I've done that as the new issue #320, in case that's something we'd like to proceed with and add. I hope you see that with #320, one can continue to use `ForEach` as it is today.

**Comment by atifaziz** [comment]
`CountDown` from #458 can help implement this:
 
```c#
Enumerable.Range(1, 10).ForEach(
	i => Console.Write(i + " "),
	i => Console.Write($"\nthird to last: {i}"),
	i => Console.Write($"\nsecond to last: {i}"),
	i => Console.Write($"\nlast: {i}"));
```

like so:

```c#
Enumerable
    .Range(1, 10)
    .CountDown(3, (i, cd)
        => cd == 2 ? $"\nthird to last: {i}"
         : cd == 1 ? $"\nsecond to last: {i}"
         : cd == 0 ? $"\nlast: {i}"
         : i + " ")
    .ForEach(s => Console.Write(s));
```

And more generally:

```c#
public static void ForEachLast<T>(this IEnumerable<T> source,
    Action<T> defaultAction, params Action<T>[] actions) =>
    source.CountDown(actions.Length, (e, cd) =>
              (Arg: e, Action: cd is int n && n < actions.Length
                             ? actions[actions.Length - n - 1]
                             : defaultAction))
          .ForEach(e => e.Action(e.Arg));
```


Since `CountDown` is “good enough” to help build such custom extensions as simple and easy compositions, I'm going to go ahead and close this. I'm also happy to re-open if there's a strong argument for reconsidering.

**Comment by leandromoh** [comment]
Greate solution with CountDown.

**Comment by atifaziz** [comment]
> your solution looks generic enough to become a new operator tô me.

Which solution and what new operator would that be? `CountDown` _is_ the underlying generic solution. The other I presented in #320 but never got any feedback.
