### ISSUE TITLE
Upgrade library to net4.5

### ISSUE THREAD

**Issue by fsateler** [morelinq/MoreLINQ#270]
Forked over from https://github.com/morelinq/MoreLINQ/issues/128#issuecomment-173109354.

@atifaziz said:

> I think we should move to .NET 4.5 but post 2.0 release

I'm not sure I fully understood, but that would break backwards compatibility for projects still targeting .net 3.5. Or was the issue really to add a new version targeting 4.5? I wonder if this issue has become moot due to netstandard1.0 is targeted? (at least `IReadonlyCollection` is present there).

**Comment by atifaziz** [comment]
If multi-targeting from a single project is easy then do we still need to make a call here? It was super easy with `project.json` and the `dotnet` CLI previews. It's not so smooth with VS 2017 but [we're over that bump now](https://github.com/morelinq/MoreLINQ/issues/261#issuecomment-292227833), no?

**Comment by fsateler** [comment]
> If multi-targeting from a single project is easy then do we still need to make a call here?

I don't think so, but I was not sure. The only question is then if the `netstandard1.0` targeting is sufficient or we should add a net45 target.

**Comment by atifaziz** [comment]
@fsateler Ah, I see what you're asking now. Since `netstandard1.0` supports `net45`, I'd say we don't need to target `net45` specifically or have a separate build for it.

**Comment by fsateler** [comment]
> Ah, I see what you're asking now. 

Sorry for being unclear. I should have included more context. Reason is to start adding optimizations for `IReadonlyCollection<T>`

> Since netstandard1.0 supports net45, I'd say we don't need to target net45 specifically or have a separate build for it.

Excellent. I'm closing this as 'already-implemented' then.

**Comment by atifaziz** [comment]
@fsateler Oh and note that the [test project targets `net451`](https://github.com/morelinq/MoreLINQ/blob/799e707ef5f2fc6f02e0acad46e491a6ff875a64/MoreLinq.Test/MoreLinq.Test.csproj#L7) (and should ideally even target .NET 4.5.2 since [4.0-4.5.1 are zombies](https://support.microsoft.com/en-gb/gp/framework_faq/en-us?wa=wsignin1.0)), which is a completely arbitrary decision. We build for .NET 3.5 but test on CLR 4. I think we can question that if ever some one comes kicking and screaming about behavioral differences observed between the two CLR versions.

**Comment by fsateler** [comment]
> Oh and note that the test project targets net451 (and should ideally even target .NET 4.5.2 since 4.0-4.5.1 are zombies), which is a completely arbitrary decision. 

I have created a PR to migrate to 4.5.2. (#271, lets see if tests pass on all platforms)

> We build for .NET 3.5 but test on CLR 4. I think we can question that if ever some one comes kicking and screaming about behavioral differences observed between the two CLR versions.

Yes, I agree. However, it appears that the .net framework build of the test project links against the .net 3.5 version of the library. What is the process for selecting the correct build to link against?

**Comment by atifaziz** [comment]
> What is the process for selecting the correct build to link against?

The decision is different for apps and libraries. Libraries get hosted in apps so the whole end-of-life of .NET versions affects apps the most. Libraries target based on API availability, so for example, [System.ValueTuple](https://www.nuget.org/packages/System.ValueTuple/4.3.0) requires 4.5 and if we ever want to benefit from C# tuples in MoreLINQ then we'd have to add or set the base target to 4.5. The test project used to be a library that was run by an NUnit runner. It [had to be turned into a self-hosted executable test runner](https://github.com/morelinq/MoreLINQ/issues/261#issuecomment-291632074) as part of #261 but I'm hoping that's just temporary. As a simple test runner, I'm less concerned about .NET Framework lifetimes as I expect CLR 2 & 4 to be fairly compatible for the kind of project that is MoreLINQ. That's why the decision there was somewhat arbitrary (why even 4.5.1?). The test project links against the library that targets 3.5 but eventually the library is being hosted by CLR 4 so not sure what the concern there is about alignment. Do you think we need a more formal process?

**Comment by fsateler** [comment]
> The test project links against the library that targets 3.5 but eventually the library is being hosted by CLR 4 so not sure what the concern there is about alignment. Do you think we need a more formal process?

The problem is that because the full framework test variant is linked against the library *built* for .net 3.5, and thus it lacks the `IReadonlyCollection` optimizations (which I'm currently working on). This suggests to me that projects targeting the full framework will similarly lack such optimizations.

**Comment by atifaziz** [comment]
@fsateler You said it clearly in the beginning:

> Reason is to start adding optimizations for `IReadonlyCollection<T>`

Somehow I lost that and digressed into just reiterating the current state of affairs. My bad. So it seems we'll have to add `net45` as a target for the library. I guess the question is then do we leave the `net35` target untested? Should we drop `net35` altogether? We can always add it back if it turns out to be a bad call. 🤔
