### ISSUE TITLE
ToDictionary overloads for key-value pairs & tuples of 2

### ISSUE THREAD

**Issue by gandhis1** [morelinq/MoreLINQ#272]
I'd like to suggest a simple feature, and hear whether you all think this is reasonable. The idea would be to overload ToDictionary for an IEnumerable<KeyValuePair<T1, T2>> or IEnumerable<Tuple<T1, T2>> such that no arguments have to passed to the function, it would simply convert it to a dictionary.

This would reduce unnecessary code, and frankly I'm surprised it's not built-in. 

```
public static Dictionary<T1, T2> ToDictionary<T1, T2>(this IEnumerable<KeyValuePair<T1, T2>> source)
{
    return source.ToDictionary(x => x.Key, x => x.Value);
}
```

I suppose the problem I'm trying to solve is reducing the length of code that looks like this. This was taken from a project I'm working on and if you know a better way, I'm all ears. 

```
cf_outputs.groundGroupNames
.Trim(new[] { '|' })
.Split('|')
.Select((x, i) => new KeyValuePair<string, int>(x.Trim(new[] { '"' }), i + 1))
.ToDictionary(x => x.Key, x => x.Value);
```

**Comment by atifaziz** [comment]
@gandhis1 [Your example](https://github.com/morelinq/MoreLINQ/issues/272#issue-220278719) could be simplified using [`Index`](https://morelinq.github.io/1.x/ref/api/html/M_MoreLinq_MoreEnumerable_Index__1_1.htm):

```c#
cf_outputs.groundGroupNames
.Trim('|')
.Split('|')
.Select(x => x.Trim('"'))
.Index(1)
.ToDictionary(x => x.Value, x => x.Key);
```

That said, I've always been tempted to add the simpler overloads you're talking about. The example above isn't a strong case for it because you needed to reverse the key-value pair but it makes sense otherwise, especially when you have a function handing you a sequence of a `KeyValuePair<,>` (well, like `Index`, if `Key` _is_ the key). Even though we avoid trivial (one-liner) wrappers, this is one of those rare cases where you wish it was part of LINQ proper because `KeyValuePair<,>` was already part of .NET before LINQ was introduced and even an integral part of [`IDictionary<,>`](https://msdn.microsoft.com/en-us/library/s4ys34ea(v=vs.110).aspx).

Tuples is another interest case that can be naturally fit to simplify the usage.

@fsateler I think we can break the no-one-liners rule here ([like it's been done `ToHashSet`](https://github.com/morelinq/MoreLINQ/blob/v2.3.0/MoreLinq/ToHashSet.cs#L38-L41)) unless you have other reservations?

**Comment by fsateler** [comment]
> @fsateler I think we can break the no-one-liners rule here (like it's been done ToHashSet) unless you have other reservations?

The only objection would be the one-liner rule. But this one is particularly common and useful, I usually add such an overload for my projects.
I think this overload is so useful it can warrant an exception to the no-one-liners rule.

**Comment by atifaziz** [comment]
If we are going to do this for `ToDictionary` then it makes sense to extend the same exception to `ToLookup`. 💭

**Comment by atifaziz** [comment]
This is now [available on NuGet as part of 2.4 beta 1](https://www.nuget.org/packages/morelinq/2.4.0-beta-01).

**Comment by atifaziz** [comment]
[Docs are now up](https://morelinq.github.io/2.4/ref/api/html/Overload_MoreLinq_MoreEnumerable_ToDictionary.htm). There is a strange issue with docs not showing up for overloads working tuples that needs investigating (any help appreciated). I noticed it stems from `MoreLinq.xml` (note the truncated `System.` cases below), which is odd because it's generated by the compiler:

```xml
<member name="M:MoreLinq.MoreEnumerable.ToDictionary``2(System.Collections.Generic.IEnumerable{System.})">
    <summary>
    Creates a <see cref="T:System.Collections.Generic.Dictionary`2" /> from a sequence of
    tuples of 2 where the first item is the key and the second the
    value.
    </summary>
    <typeparam name="TKey">The type of the key.</typeparam>
    <typeparam name="TValue">The type of the value.</typeparam>
    <param name="source">The source sequence of couples (tuple of 2).</param>
    <returns>
    A <see cref="T:System.Collections.Generic.Dictionary`2"/> containing the values
    mapped to their keys.
    </returns>
</member>
<member name="M:MoreLinq.MoreEnumerable.ToDictionary``2(System.Collections.Generic.IEnumerable{System.},System.Collections.Generic.IEqualityComparer{``0})">
    <summary>
    Creates a <see cref="T:System.Collections.Generic.Dictionary`2" /> from a sequence of
    tuples of 2 where the first item is the key and the second the
    value. An additional parameter specifies a comparer for keys.
    </summary>
    <typeparam name="TKey">The type of the key.</typeparam>
    <typeparam name="TValue">The type of the value.</typeparam>
    <param name="source">The source sequence of couples (tuple of 2).</param>
    <param name="comparer">The comparer for keys.</param>
    <returns>
    A <see cref="T:System.Collections.Generic.Dictionary`2"/> containing the values
    mapped to their keys.
    </returns>
</member>
```

**Comment by atifaziz** [comment]
Missing tuple documentation is an issue with the C# compiler (see dotnet/roslyn#18274) so not much we can do about it but at least it is addressed for the next version.
