### ISSUE TITLE
Insert a sequence within another

### ISSUE THREAD

**Issue by leandromoh** [morelinq/MoreLINQ#306]
This issue proposes the function `InsertAt` that is similar to `List<T>.InsertRange`, but it differs into 2 points:

1 - `List<T>.InsertRange `throws exception when `index > list.Count`, In this case `InsertAt `just acts like Concat:

`[1,2].InsertAt([3,4], 9999); // [1,2,3,4]`

2 -` List<T>.InsertRange` throws exception when `index < 0`, in this case `InsertAt `understand -1 as "the end of the sequence", -2 as "last to one" index, etc...

```
[1,2].InsertAt([3,4], -1); // [1,2,3,4]
[1,2].InsertAt([3,4], -2); // [1,3,4,2]
[1,2].InsertAt([3,4], -3); // [3,4,1,2]
```

Signature:

`static IEnumerable<T> InsertAt<T>(this IEnumerable<T> source,  IEnumerable<T> second, int index)`

Usage:

```
[ 1, 2, 5, 6 ].InsertAt([ 3, 4 ], 2) // [1, 2, 3, 4, 5, 6]

var slc = list.Slice(x, y);
var exc = list.Exclude(x, y);
exc.InsertAt(slc, x) == list; // true 
```

**Comment by atifaziz** [comment]
> 1 - `List<T>.InsertRange `throws exception when `index > list.Count`, In this case `InsertAt `just acts like Concat:

This would be strange. I'd expect such a function to insert at exactly the requested index. If the source sequence is shorter then it should pad it up to the index with defaults before concatenating the second sequence.

**Comment by leandromoh** [comment]
I did not think this way, but make sense.
Therefore, I think it is a good idea to have another overload where user can specify the value for padding.
What do you think?

**Comment by atifaziz** [comment]
> have another overload where user can specify the value for padding.

You could also make an index that's out of range an error condition and then people can just combine [`Pad`](https://morelinq.github.io/1.x/ref/api/html/Overload_MoreLinq_MoreEnumerable_Pad.htm) before `InsertAt` if they want to avoid the error.

**Comment by leandromoh** [comment]
> You could also make an index that's out of range an error condition and people can just combine Pad before InsertAt if they want to avoid the error.

This would be a suprise. LINQ operators only throws exceptions when there is no alternative (when they really can't carry on). For example, all the following cases might throw an error, but they do not. 

1. a non sense value like `-1` for `Take` or `Skip`, 
2. two different-lenght enumerables for `Zip`, 
3. pass a number greater than enumerable's `Count` to `Take` 

So, as you said, make sense that, _at least,_ `InserAt` pad the sequence with _defaults_ to do its job.

In addition, I dont see any advantage, or reason to force user to combine `Pad `with `InsertAt` to avoid errors. If we can make `xs.InsertAt(ys, 10, -1)` has the same effect of `xs.Pad(10, -1).InsertAt(ys, 10)`, why not?

**Comment by leandromoh** [comment]
I was thinking... We have two main possible behavior for `InsertAt` when sequence is shorter than the passed `Index`:

A. behave like concat 
B. Pad up the sequence (with _default_ or user passed value)  before concatenate


If we choose behavior A, user can reach behavior B simply applying `Pad` function before concatenate.
`xs.Pad(index).InsertAt(ys, index)`

However, If we choose behavior B, There is no optimal way to do to reach behavior A (none that iterate enumerate once, at least).
`xs.AtLeast(index) ? xs.InsertAt(ys, index) : xs.Concat(ys)`

So analysing these two approach, I see the first is more viable/flexible to user.

IMO, it would be nice dont create new elements to the sequence, that is, 
`result.Count()` must always be equals to `source.Count() + second.Count()`

I agree that it is a bit strange that `xs.InsertAt(ys, index)` dont put `ys` in the `index` position if `xs` is shorter, but I think it is more viable/flexible to user and make more sense to me just concat. Maybe the strange that @atifaziz said occurs because of the name of the function, if so, I can think a new name to it, a new one that reflect better the intention.

**Comment by atifaziz** [comment]
> This would be a suprise. LINQ operators only throws exceptions when there is no alternative (when they really can't carry on).

I think `InsertAt` is different than the operators you cited. The closest apple-to-apple comparison would be with `ElementAt` that takes an index and does throw if it is out of range.

**Comment by leandromoh** [comment]
All quoted operators receive a list and returns a list, such as InsertAt does, that is, they all are about list transformation. So looks me an apple-to-apple comparation. 

ElementAt is not about list transformation. It throw exception in fact because It hás tô return 2 informations tô user: If It found the element and its value (like a dictionay.TryGetValue). Since there was no tuples avaible and an out parameter would be pretty weird for a linq method, the only way is to throw an exception. If c# had a maybe or option like Haskell and f# have, surely It would use It inatead throw exception (like haskell and f# do in their ElementAt analogue funxtions).

**Comment by atifaziz** [comment]
Okay, I agree it should have a well-defined behaviour in all cases instead of throwing an exception. What bothers me are two things:

1. Overloaded behaviour; it doesn't do just one thing and only what it says
2. Using a positive and negative index to mean different things

> Maybe the strange that @atifaziz said occurs because of the name of the function, if so, we can think a new name to it, a new one that reflect better the intention.

That is a problem. The name and expected behaviour don't match.

> but I think it is more viable/flexible to user and make more sense to me just concat.

Sometimes the flexibility isn't just needed. Other times, it can be plain dangerous, e.g. an index computed at run-time can change the result if it's positive or negative. If a negative index is changed to mean the same at 0 or start or list and a positive one is absolute (with padding) then `InsertAt` becomes dead simple to reason about.

**Comment by fsateler** [comment]
I'd find it very surprising if a function called `InsertAt` did anything but throw if the source sequence is shorter than the required index. Extending with default values can be trivially done by prepending `Pad`. Achieving "Insert or Concat" functionality would be harder. But I would then argue that this is fundamentally a different operation, thus requiring a different operator (much like `PartialSort` is a separate operator than the combination of `Take` and `OrderBy` and is not an overload of either).

I don't have a fundamental problem with having negative indices mean "start from the end", as there is some "previous art" doing so, like python. However, I think it would be best if "start from the end" behavior was controlled by a separate, enum parameter (default start from the start). Having indices start at 0 but "end" at -1 has always seemed weird to me, and made offset counting harder than necessary.

**Comment by atifaziz** [comment]
> "start from the end" behavior was controlled by a separate, enum parameter

We've been here before in #24. You almost never need an enum.

We have `Take(n)` and `TakeLast(n)` to grab items from either at the head or at the tail, not `Take(n)` and `Take(-n)` to mean the same. You make that decision generally at coding-time. For the rare occasions when you really need to do it dynamically at run-time, it's easy to do so:

```c#
var items = count < 0 ? source.TakeLast(-count)
                      : source.Take(count);
```

**Comment by fsateler** [comment]
> > "start from the end" behavior was controlled by a separate, enum parameter
>
> We've been here before in #24. You almost never need an enum.
>
>We have `Take(n)` and `TakeLast(n)` to grab items from either at the head or at the tail, not `Take(n)` and `Take(-n)` to mean the same. You make that decision generally at coding-time

Well, we do add an `OrderByDirection`. However, I agree that most of the time the decision (for `InsertAt`) will be made at coding time and thus a parameter is not needed. My main objection was to the use of negative indices though. I'm neutral on whether this is done with an enum parameter or a different operator.

**Comment by atifaziz** [comment]
@fsateler We are on the same page. 👍 

> we do add an `OrderByDirection`

True and I don't think it should've been added (just so that it doesn't become a model or excuse for more enums to creep into the API) but it was very specific, small in scope & well-defined so really just harmless. I can't speak for everyone but I've never felt/had the need for it.

**Comment by leandromoh** [comment]
> We have Take(n) and TakeLast(n) to grab items from either at the head or at the tail, not Take(n) and Take(-n) to mean the same.

Make sense to have a separated method for `TakeLast` because `Take` receive a `count` (quantity), and we can take nothing in a negative quantity. Talking about indexes (position) make sense sinse `-n` is just a suggar for another position  (`source.Count() - n`), that is, the behavior remains the same. But for `Take` it is not true: `source.Take(-1) != source.Take(source.Count() - 1)`. As @fsateler said, some methods of some languages accepts this suggar. My original idea about negative index for `InsertAt` came from `slice` Javascript's method.

About the 2 scenarios/behavior (`Concat` x `Pad) when sequence is shorter than the passed Index `, I think everybody agree that the better approach is different operator. But 

1 which behavior would be the default for `InsertAt`? 
2 will we change the function name for reflect better its behavior? 
3 what is the final conclusion about negative indexes as suggar for `Count() - index`? (my vote is favor)

**Comment by atifaziz** [comment]
> Talking about indexes (position) make sense sinse `-n` is just a suggar for another position  (`source.Count() - n`), that is, the behavior remains the same. 

Why does it make sense for index and not for count? Sugar is sugar and you can coat just about anything with it. And when you get into sugar and candy then the discussion usually gets subjective.

> and we can take nothing in a negative quantity.

No you can't, speaking strictly, but you can always technically overload the semantics and that's what you're proposing with a negative index.

> But for `Take` it is not true: `source.Take(-1) != source.Take(source.Count() - 1)`. 

That was just to illustrate a point. I wasn't saying it _is so_ but that it _could have been designed so_:

```c#
public static IEnumerable<T> Draw<T>(this IEnumerable<T> source, int count) =>
    count < 0 ? source.TakeLast(-count) : source.Take(count);
```

…yet it _isn't so_, so there! 😆

> My original idea about negative index for `InsertAt` came from `slice` Javascript's method.

I understand the source of your inspiration. [I have written similar methods in the past](https://bitbucket.org/raboof/mannex/src/eb3d025bb06a7a8ff42e640dd4fbf3746d77145f/src/String.cs?at=default&fileviewer=file-view-default#String.cs-106:160), even [libraries](https://github.com/atifaziz/AngryArrays). Taking inspiration from elsewhere is a good thing, but when in Rome, I'do as Romans. In other words, I would adapt to the spirit of LINQ and naturally lean towards strict semantics since practically all methods on core types in .NET that deal with indexes, counts & ranges validate for boundary conditions.

> 1 which behavior would be the default for `InsertAt`? Concat or Pad?

Definitely not `Concat`. I can live with making padding integral (preferred & [convinced](https://github.com/morelinq/MoreLINQ/issues/306#issuecomment-306455091)) or forcing the use of `Pad` to avoid an exception in the event that the index is out of range.

BTW, have you ever looked at [`Seq.skip`](https://msdn.microsoft.com/en-us/visualfsharpdocs/conceptual/seq.skip%5b't%5d-function-%5bfsharp%5d) and [`Seq.take`](https://msdn.microsoft.com/en-us/visualfsharpdocs/conceptual/seq.take%5b't%5d-function-%5bfsharp%5d) in F#? Unlike in LINQ, they throw exceptions if the sequence doesn't have sufficient count of elements to skip or take. It still bites me from time to time when I switch between C# and F#, especially because the names match exactly those in LINQ. While there's still [`Seq.truncate`](https://msdn.microsoft.com/en-us/visualfsharpdocs/conceptual/seq.truncate%5B't%5D-function-%5Bfsharp%5D) that acts like `Take` in LINQ, there's no built-in equivalent of `Skip` that doesn't throw.

> 2 will we change the function name for reflect better its behavior? 

I don't have any proposal given the mixed modes of operation.

> 3 what is the final conclusion about negative indexes as suggar for `Count() - index`? (my vote is favor)

:-1:

**Comment by leandromoh** [comment]
Followin the same way of swapRange, i Will submit a PR for this with the strict scenario. We can relax the rules with another PR If we think valid

**Comment by leandromoh** [comment]
Just a doubt... when the index is greater than source's length `InsertAt `must throw. Ok. But in which of the following sceneario?

1. throw together with the other null validations (and therefore, we must consume `source` before the result's iteration to check if it has at least `N` elements, and  `InsertAt ` will not pass in a lazy test ) 
2. throw only when user will iterate the N nth (that not exist), that is, the following code dont throw `Enumerable.Range(0, 7).InsertAt(new[] { 97, 98, 99 }, 8).Take(5)`

**Comment by atifaziz** [comment]
This is now [released as part of version 2.9.0](https://github.com/morelinq/MoreLINQ/releases/tag/v2.9.0). Apologies that it has taken this long. I had completely forgotten to make the release. 🤦‍♂️

**Comment by leandromoh** [comment]
Dont worry. I would like to see Flatten in 2.9 too.
Do you think possíble?

**Comment by atifaziz** [comment]
@leandromoh I am afraid not, as 2.9 is already released.

**Comment by leandromoh** [comment]
Sorry,  I mean in next release

**Comment by atifaziz** [comment]
@leandromoh Yes, sure. Happy to ship it as soon as the PR is ready to merge, even if it means shipping a single new operator, as it was done in [2.9](https://github.com/morelinq/MoreLINQ/releases/tag/v2.9.0).
