### ISSUE TITLE
Consider adding ToObservableCollection operator

### ISSUE THREAD

**Issue by Marcossi** [morelinq/MoreLINQ#308]
In MVVM is very common the use of ObservableCollection but does not exist this method.

Since there are ToDictionary, ToHashSet, ... could it be a good option to add ToObservableCollection?

Thanks by this excelent library!

**Comment by atifaziz** [comment]
We generally avoid one-line helpers and that's what `ToObservableCollection` would be.

`ToDictionary` and `ToHashSet` are exceptions to the rule. For `ToDictionary`, see #272. `ToHashSet`, [which is a true one-liner](https://github.com/morelinq/MoreLINQ/blob/1.4/MoreLinq/ToHashSet.cs#L57), is there for a more subtle reason ([besides a historical one](https://github.com/morelinq/MoreLINQ/commit/f93bf9bae3430b8c9066af4815026ccffe57dcfc) :smile:). When working with anonymous types in a query, you cannot use the `HashSet<T>` constructor because you can't supply a type argument for the type parameter `T`. The only way to make it work is via an extension method and to rely on the compiler to infer that actual `T`. `ToObservableCollection`, on the other hand, is almost always going to be used at the end of a chain (it's a collection inherently designed for observing side-effects and wouldn't do any good _within_ a query) and practically never for an anonymous type so I don't find it warrants an exception.

**Comment by atifaziz** [comment]
Also should add that under .NET 3.5, [`ObservableCollection<>` requires a dependency on `WindowsBase.dll`](https://msdn.microsoft.com/en-us/library/ms668604(v=vs.90).aspx) as it was introduced as part of WPF back then. Anyway, [the fact that it found its home in `System.dll` with .NET 4.0](https://msdn.microsoft.com/en-us/library/ms668604(v=vs.100).aspx) does not change anything.

**Comment by atifaziz** [comment]
Closing unless there's a good argument to re-consider.
