### ISSUE TITLE
MoreLINQ's Prepend conflicts with LINQ's Prepend

### ISSUE THREAD

**Issue by baltie** [morelinq/MoreLINQ#371]
Enumerable.Prepend appeared in .NET Framework 4.7.1 and is part of .NET Standard 2.0. I now have to specify if I want the MoreLinq og LINQ version, which leads to uglier code.

There might be others too (Append?), but this is the one I noticed.

I'm using morelinq 2.10.0.

**Comment by atifaziz** [comment]
This is an inherent problem with extension methods and not an issue specifically caused by MoreLINQ, especially since MoreLINQ had `Prepend` way before .NET. That said, this is something we're looking to address and so I would welcome you to join or subscribe to the conversation in #214.

> There might be others too (Append?)

Luckily, `Append` is not an issue since we called it [`Concat`](http://morelinq.github.io/1.x/ref/api/html/M_MoreLinq_MoreEnumerable_Concat__1.htm) 😅 but I agree, the situation may worsen with time.
