### ISSUE TITLE
ForEachSafe operator 

### ISSUE THREAD

**Issue by leandromoh** [morelinq/MoreLINQ#404]
Sometimes we need to process a sequence as much as we can, that is, **even an exception occurs**, we must "process" the rest of the elements. I needed it one of this days and I imagine it is not a uncommon scenario. 

scenario :

```c#
foreach (var element in source) 
{ 
 // action that might throw
}
```
example of error:

```c#
Enumerable.Range(1, 20).ForEach(x =>
{
    if (x % 7 == 0)
        throw new InvalidOperationException();
    else
        Console.WriteLine(x);
})
```

here we can process/print all elements except 7 and 14, but when we reach 7, everything stops.

solution 1:

```c#
foreach (var element in source) 
{ 
      try
      {
          // do something with element, what might throws
      }
      catch (Exception ex)
     {
         // do something with element / exception
     }
}
```

So I propose a new operator that do this handling and return a sequence with the elements that threw as well their exceptions.

Propose signature:

```c#
public static IEnumerable<KeyValuePair<T, Exception>> ForEachSafe<T>(this IEnumerable<T> source, Action<T> action)
```

Example of usage:

```c#
Enumerable.Range(1, 20)
.ForEachSafe(x =>
{
    if (x % 7 == 0)
        throw new InvalidOperationException();
    else
        Console.WriteLine(x);
})
.ForEach(p => Console.WriteLine($"item {p.Key} throws: {p.Value}"));
```

I would like to submit a PR for this. What do you think?

PS: the operator name is not defined yet;

**Comment by atifaziz** [comment]
What's wrong with solution 1? Your `ForEachSafe` doesn't seems to be solving the problem laid our in your scenario because it returns erroneous elements.

**Comment by leandromoh** [comment]
Solution 1 works. 

The advantage of `ForEachSafe`, is that one dont need to write a `try catch`, and, at a query chain, deal with exceptions in a LINQ manner. 

Also, if user will do nothing with the exception in the `catch` block, one can use `ForEachSafe `as simple as `ForEach` operator, avoind the boilerplate code.

**Comment by atifaziz** [comment]
> deal with exceptions in a LINQ manner.

The way to deal with exceptions in a LINQ manner would be to treat them as part of computation and it should be disconnected from `ForEach` so it's more generally applicable.

**Comment by leandromoh** [comment]
As well the propose `Available` operator, the computation may be done by some code that's not under your control.

Here is the scenario that motivated me:

```c#
int Update<T>(IEnumerable<T> source)
{
  var errorsCount = 0;
  foreach(var e in source)
  {
    try
    {
        process(e);
    }
    catch(Exception ex)
    {
       errorsCount++;
       log(e, ex.Message);
    }
  }
  return errorsCount;
}
```

will become :

```c#
int Update<T>(IEnumerable<T> source) => 
   xs.ForEachSafe(process)
      .Pipe(p => log(p.Key, p.Value.Message))
      .Count()
```

**Comment by atifaziz** [comment]
> …the computation may be done by some code that's not under your control.

I think you're misunderstanding me. I'm saying that the success/failure of an operation should be part of the results.

> can deal with exceptions in a LINQ manner (similar to `Prepend` operator).

How does `Prepend` help deal with exceptions?

I don't find anything wrong with your `Update` version with `foreach` and `try`/`catch`. It's the way it should be done. `ForEachSafe` seems to be supporting a very specific need and should remain local to your project. I don't think the job of MoreLINQ is to help with third-party code that doesn't fit its model, especially in a non-generic and non-composable way. `ForEach` is a side-effect causing query terminator and another version that returns results will be confusing at best.

Now if you put `ForEach` aside for a moment, my feeling is that what you really want here is a `SelectWithError`:

```c#
public static IEnumerable<TResult> SelectWithError<T, TException, TResult>(
    this IEnumerable<T> source,
    Func<T, TResult> resultSelector,
    Func<T, TException, TResult> errorSelector)
    where TException : Exception =>
    source.SelectWithError(resultSelector, delegate { return true; }, errorSelector);

public static IEnumerable<TResult> SelectWithError<T, TException, TResult>(
    this IEnumerable<T> source,
    Func<T, TResult> resultSelector,
    Func<T, TException, bool> errorPredicate,
    Func<T, TException, TResult> errorSelector)
    where TException : Exception
{
    return source.Select(e =>
    {
        try
        {	        
            return resultSelector(e);
        }
        catch (TException ex) when (errorPredicate(e, ex))
        {
            return errorSelector(e, ex);
        }
    });
}
```

Let's assume for the sake of a simple example that the third-party code here is [`byte.Parse`](https://docs.microsoft.com/en-us/dotnet/api/system.byte.parse). An example usage would be as follows:

```c#
var errorCount =
    "l,2,3,4,S,6,7,B,9,300"
       .Split(',')
       .SelectWithError(s => (s, byte.Parse(s), null),
                        (_, e) => e is FormatException || e is OverflowException,
                        (string s, Exception e) => (Input: s, Output: 0, Error: e))
       .Where(r => r.Error != null)
       .Pipe(r => Console.Error.WriteLine(r.Input + ": " + r.Error.Message)) // log
       .Count();
Console.Error.WriteLine(errorCount + " error(s)");
```

Point is, `SelectWithError` is more generally applicable, doesn't cause side-effects (in fact contains them), and composable. If `SelectWithError` isn't what you're after then I think we should close this issue because I don't think `ForEachSafe` belongs in this library in its currently proposed form.

**Comment by leandromoh** [comment]
> How does Prepend help deal with exceptions?

It does not. I meant that `Prepend `help us to let the query chain more queryable.

Putting side-effect aside, I think that `SelectWithError` is the most generally applicable operator we can create for this scenario.

I will close this issue. Would you be interested in a PR ?
