### ISSUE TITLE
Shuffle: RandomSubset overload without subset size

### ISSUE THREAD

**Issue by leandromoh** [morelinq/MoreLINQ#470]
I saw #409 by @MkazemAkhgary and looking into `RandomSubset` implementation I noted that case user wants to shuffle a sequence entirely, one can use `RandomSubset` operator, but it forces user evaluate a lazy sequence twice, for example.

```c#
// lazy sequence, that may be expensive
var source = Enumerable.Range(1, 10);

// first iteration to get the length of sequence
var size = source.Count(); 

// second iteration (there is a ToArray() inside RandomSubset to avoid change original source)
var shuffle = source.RandomSubset(size); 
```

I propose the new Shuffle operator:
```c#
IEnumerable<T> Shuffle<T>(IEnumerable<T> sequence)
```

This have the following advantages:

1. semantically correct (user wants shuffle sequence entirely, not a subset)
2. avoid unnecessary computations (iterates source once)
3. less code for user write

**Comment by leandromoh** [comment]
@atifaziz?

**Comment by fsateler** [comment]
I think this is useful. About the naming, what do other languages/toolkits/libraries have for equivalent functionality?

**Comment by atifaziz** [comment]
@leandromoh Makes sense. If there was a `Shuffle` in MoreLINQ then `RandomSubset` would have been called `PartialShuffle` but it's a bit late in the day for that. I think `Shuffle` is a good name because a `RandomSubset` overload without the subset size parameter will look weird since there won't be any sub-setting. Question then is if we want to have `RandomSubset` as an alias for `PartialShuffle` or leave it as-is. I'd rather mark the former obsolete if it's going to be an alias but not drop it for 3.0. This can be discussed separately. Meanwhile, `Shuffle` is a good compromise.

> what do other languages/toolkits/libraries have for equivalent functionality

I think [_shuffle_ is a safe bet](http://rosettacode.org/wiki/Knuth_shuffle).

**Comment by leandromoh** [comment]
Good. I will submit a PR.
