### ISSUE TITLE
Operator to skip erroneous elements during iteration

### ISSUE THREAD

**Issue by leandromoh** [morelinq/MoreLINQ#515]
Sometimes some elements of a sequence can not be accessed, but the enumeration simples breaks, not allowing to carry on with the other avaible elements. This new method allow ignore especific type of erros (i.e. exceptions), What can be very useful if the exception is thrown by some third-party code that's not under your control.

## Scenario

The scenario bellow print only 1, while it could print all (available) odd elements.
```c#
var source = Enumerable.Range(1, 10)
                       .Select(x => x % 2 == 0 ? throw new InvalidOperationException() : x);

source.ForEach(Console.WriteLine);
```

## Signature

```c#
public static IEnumerable<T> IgnoreErrors<T, TException>(
            this IEnumerable<T> source,
            Func<TException, bool> errorPredicate)
            where TException : Exception
```

## Example

the code bellow prints all odd elements, skipping every exception of type `InvalidOperationException` by a predicate that always return true.

```c#
source.IgnoreErrors(InvalidOperationException ex => true).ForEach(Console.WriteLine)
```

## Workaround

None

**Comment by atifaziz** [comment]
:memo: Forked from #405.

**Comment by atifaziz** [comment]
I think `IgnoreErrors` is a poor name. Consider instead (in order of preference):

1. `MoveNextOnError`
2. `SkipErroneous`
3. `IgnoreErroneous`

🤔

The problem with `IgnoreErrors` is that it talks about _errors_ rather than elements! It says errors are ignored but that doesn't say what happens to the elements. The word _erroneous_ is an adjective and therefore describes the elements that will be either skipped (`SkipErroneous`) or ignored (`IgnoreErroneous`).

**Comment by Orace** [comment]
I think using `Error` in the method name is a poor idea, it's about exception not errors.
A good name to handle exceptions is catch.

A pleasant use would look like this :

    enumerable.Catch<Exception>().ToList()

But since the type of the element will be lost we are forced to write :

    enumerable.Catch<TElement, Exception>().ToList()

A workaround is to introduce a new type implementing `IEnumerable<T>` let's call it `TryEnumerable<T>`, it's a wrapper of the sour enumerable and will be made by a call to the `Try` extension method.

    enumerable.Try().Catch<Exception>().ToList()

At this point Catch is a method of TryEnumerable<T> (it can't be an extension method or the problem of missing element type will appear again).

We can the introduce different Catch overload.

    Catch<Exception>()                          // The element will be ignored
    Catch<MyException>(fallBackValue) // The element will be replaced by a fallback value
    Catch<MyException>(ex => ex.FallBackValue)  // The element will be replaced by a fallback value computed from the exception information
    CatchIf<MyException>(ex => !ex.IsRealyImportant) // The exception will be swallowed only if required (OP requested behavior)
    CatchIf<MyException>(ex => !ex.IsRealyImportant, ex => ex.FallBackValue)

All catch method returns a new `TryEnumerable<T>` with the new behavior.
It's possible to chain it.

    enumerable.Try().Catch<FileNotFoundException>().Catch<PathTooLongException>(....)

If multiple catch match the `Exception`, the first one win :

    enumerable.Try()
        .Catch<Exception>(42)          // will catch all exception and fall back to 42
        .Catch<MyException>(420);  // will never be reached

**Comment by Orace** [comment]
After many test I'm for closing the issue.
The behavior of an enumerator after an exception is not homogeneous in the framework.

For enumerator made using `yield` keyword a state machine is build (see [this](https://startbigthinksmall.wordpress.com/2008/06/09/behind-the-scenes-of-the-c-yield-keyword/)) :

    case _N_:
      state = -1;     // enumerator is consumed
      current = ...;  // evaluation of the next value that possibly throw the exception
      state = _N+1_;  // ready for the next state
      return true;

Then we can see that, if the evaluation of the next value throw, the enumeration is consumed and calls to `MoveNext` will always return false.

For instance [Take](https://referencesource.microsoft.com/#System.Core/System/Linq/Enumerable.cs,ceb7d3d4f0a39720) and [Skip](https://referencesource.microsoft.com/#System.Core/System/Linq/Enumerable.cs,83ec6a20321060a1) are coded like that.

But not [Select](https://referencesource.microsoft.com/#System.Core/System/Linq/Enumerable.cs,257), it's a hand written state machine and the [call to the selector](https://referencesource.microsoft.com/#System.Core/System/Linq/Enumerable.cs,296) is not protected by temporary terminal state like above.

This give different behavior.

        // lets try to divide by 0 in the middle of a sequence
        Test(Enumerable.Range(-1, 3).Select(v => 1 / v).Catch()); // -1,1 as expected
        Test(Enumerable.Range(-1, 3).Select(v => 1 / v).Take(3).Catch()); // -1 only
        Test(Enumerable.Range(-1, 3).Select(v => 1 / v).Skip(0).Catch()); // -1 only

This is true for .NET 4.7.2 not .NET core

The different implementations, of linq are not ready for this.
Ultimately a `yield throw` is missing in the language to allow user to easily build exception recoverable enumerable.

**Comment by atifaziz** [comment]
@Orace Thanks for that research! Glad to see you arrived at the [same conclusion as I did](https://github.com/morelinq/MoreLINQ/pull/503#pullrequestreview-132869429) on the PR #515.

I will close this now as abandoned.

**Comment by Gladskih** [comment]
Even if this Try().Catch<>() cannot ignore inner enumerator exception in deterministic manner it still could be useful for retrowing custom exception when for some reason you return your IEnumerable to some framework (e. g. [Kafka Streams](https://github.com/LGouellec/kafka-streams-dotnet)) and want to provide layer specific information for outer handler.
