### ISSUE TITLE
Append conflicts with Enumerable.Append()

### ISSUE THREAD

**Issue by Sam558** [morelinq/MoreLINQ#527]
I am new to MoreLINQ, I want to use "official" LINQ and MoreLINQ side by side.  They both have Append() method.  for below code 

`Enumerable.Range(1,5).Append(6);`

I got compiler error:

Cannot execute text selection: CS0121 The call is ambiguous between the following methods or properties: 'System.Linq.Enumerable.Append<TSource>(System.Collections.Generic.IEnumerable<TSource>, TSource)' and 'MoreLinq.MoreEnumerable.Append<T>(System.Collections.Generic.IEnumerable<T>, T)'

any solution?

**Comment by leandromoh** [comment]
MoreLINQ can be used in one of two ways. The simplest is to just import the
`MoreLinq` namespace and all extension methods become instantly available for
you to use on the types they extend (typically some instantiation of
`IEnumerable<T>`). In some very rare instances, however, this cause conflicts
with other libraries you may be using that incidentally also extend the same
type with an identically named method and signature. This happened with
MoreLINQ, for example, when Microsoft .NET Framework 4.0 introduced
[`Zip`][netzip] and [MoreLINQ already had one][zip]. Starting with version 3.0
of MoreLINQ, you can reduce the potential for present (or even future)
conflicts by individually importing just the extension methods you need using
the [static imports feature introduced in C# 6][using-static]:

```c#
using static MoreLinq.Extensions.LagExtension;
using static MoreLinq.Extensions.LeadExtension;
```

In the example above, only the [`Lag`][lag] and [`Lead`][lead] extension
methods will be available in scope.

Apart from extension methods, MoreLINQ also offers regular static method
that *generate* (instead of operating on) sequences, like `Unfold`,
`Random`, `Sequence` and others. If you want to use these while statically
importing other individual extension methods, you can do so via aliasing:

```c#
using static MoreLinq.Extensions.LagExtension;
using static MoreLinq.Extensions.LeadExtension;
using MoreEnumerable = MoreLinq.MoreEnumerable;
```

In the example above, [`Lag`][lag] and [`Lead`][lead] will be available as
extension methods as well as all the regular static methods on
`MoreEnumerable` but _without_ any of the extension methods offered by
`MoreEnumerable`.

**Comment by voxoid0** [comment]
Having to manually do a static import rather than being able to continue to use tooling's auto-import, while it makes a work-around possible, is still a big pain and a slow-down. Furthermore it seems that some cases of using methods from both Linq and MoreLinq are only resolvable by calling the extension method from the static class name directly, rather than using it as an extension of IEnumerable. 

For this reason I propose that in the next major version of MoreLinq, the conflicting method names be renamed where they may cause this conflict.

**Comment by atifaziz** [comment]
> some cases of using methods from both Linq and MoreLinq are only resolvable by calling the extension method from the static class name directly

@voxoid0 Do you have examples of those cases?

> For this reason I propose that in the next major version of MoreLinq, the conflicting method names be renamed where they may cause this conflict.

This will be a never-ending chase because the conflicts can occur with any library, not just between `System.Linq` and `MoreLinq`. The problem needed solving in a generlised manner and it took many (elapsed) years of thinking and labour (see #214 and #235) to come up with and especially commit to an acceptable solution. It might be a pain and slow to do the static imports but I believe anyone would prefer that safety any day over potential present & future conflicts, as well as breaking changes. Perhaps and eventually, this is [an issue to be taken up with the C# design team](https://github.com/dotnet/csharplang/issues) rather than libraries with extensions. Meanwhile, I propose instead to fix this via tooling if someone has the itch and the time. This can be done, for example, as a [C# analyser](https://docs.microsoft.com/en-us/visualstudio/extensibility/getting-started-with-roslyn-analyzers?view=vs-2019) for the IDE. It could be, I think, made to be MoreLINQ-specific or not.

**Comment by voxoid0** [comment]
It is indeed a difficult problem. Do you know of specific other libraries that also create conflicts? I haven't ran into any other conflicts beside with System.Linq. Also the *Extension solution still doesn't prevent having to sometimes call the extension method directly from the static class name, which disrupts the functional flow for which we use Linq/MoreLinq. While conflicts _can_ occur with other libraries, it seems far rarer than the conflicts with System.Linq which we can more easily track. Heh, this definitely depends on each programmer's perspective, habits, preferences as to which solution is most desirable. And like myself, we probably all feel strongly one way or another :P . I like to be able to write functional code without having to stop and assign a variable from a static class method call, or go to the top of the file and type a static import and hope I won't have to still call a static class method directly; this is more valuable to me than having to occasionally update my MoreLinq code if I decide to upgrade to the next major/breaking version. It'd be interesting to know where the votes would favor. I'm willing to accept if most people prefer the current solution; but I'd sure like the no-conflicts solution to have a chance.

**Comment by jspinella** [comment]
I just ran into this issue today with SkipLast. SkipLast was introduced by Microsoft to Linq with .NET Core 2.0 and is supported in .NET Standard 2.1+.

I agree with @atifaziz in that it isn't really realistic to alter one's library so as to not conflict with another's library; however since the other "library" is .NET Core I think SkipLast should be removed from the .NET Core/.NET Standard versions of MoreLinq. Keep it in the .NET Framework version of course. 

In the meantime it's easy enough to do something like `.Take(components.Count() -1)` instead of `SkipLast(1)` (although it isn't quite as robust).

**Comment by ensisnoctis** [comment]
> I agree with @atifaziz in that it isn't really realistic to alter one's library so as to not conflict with another's library; however since the other "library" is .NET Core I think SkipLast should be removed from the .NET Core/.NET Standard versions of MoreLinq. Keep it in the .NET Framework version of course.

That's what we've been trying to tell the author in https://github.com/morelinq/MoreLINQ/issues/565! It [should be possible to multitarget](https://docs.microsoft.com/en-us/dotnet/core/tutorials/libraries#how-to-multitarget) MoreLINQ for different .NET versions (with different sets of `System.Linq` extensions methods), but @atifaziz suggests workarounds instead. I still hope he will reconsider...

**Comment by Baccanno** [comment]
Same here

**Comment by gurustron** [comment]
There is also a trick with imports inside namespaces, though it is a bit esoteric to my taste, but if you have too many imports:

```csharp
// ... common imports
using MoreLinq.Extensions;

namespace YourNameSpace;
{
    using System.Linq; // default LINQ methods will be preferred
    // code using LINQ
}
```
