### ISSUE TITLE
Support for IsIncreasing and IsDecreasing

### ISSUE THREAD

**Issue by anuviswan** [morelinq/MoreLINQ#532]
Can validate if the sequence is sorted in a particular order.

**Comment by anuviswan** [comment]
**Prototype**
```
public static bool IsIncreasing<TSource>(this IEnumerable<TSource> data) 
{ 
   return data.Zip(data.Skip(1),(first, second) => Comparer.Default.Compare(first,second) < 0).All(b => b);
}
 
 
public static bool IsDecreasing<TSource>(this IEnumerable<TSource> data)
{
   return data.Zip(data.Skip(1),(first, second) => Comparer.Default.Compare(first,second) > 0).All(b => b);
}
```

**Comment by atifaziz** [comment]
You can replace `Zip` and `Skip` with `Pairwise` to make the implementation trivial (with the added benefit that the sequence is not iterated twice):

```c#
public static bool IsIncreasing<T>(this IEnumerable<T> source) =>
    source.Pairwise((a, b) => Comparer<T>.Default.Compare(a, b) < 0).All(f => f);

public static bool IsDecreasing<T>(this IEnumerable<T> source) =>
    source.Pairwise((a, b) => Comparer<T>.Default.Compare(a, b) > 0).All(f => f);
```

So now I'd argue that it is possibly too trivial (one-liners) to warrant the effort of adding them to MoreLINQ.

As an aside, how would you define these when the source sequence is empty or only has one element? As proposed, `IsIncreasing` and `IsDecreasing` will return `true` for both; not sure that's intentional.

**Comment by anuviswan** [comment]
Well, honestly I wasn't aware of Pairwise. Yes, it does make it one-liner, but it might make life more easier enable developers to focus on other things. For example, if one is working on implementing the Nelson rule, where many rules revolve around increasing/decreasing orders.  

Regarding Empty/Single Element, the implementation was intentional, though it is worth to debate whether value should be true or false.

Would be interested to know your thoughts on both topics.

**Comment by anuviswan** [comment]
I agree. Would like to close this request if am allowed to do so.
