### ISSUE TITLE
Define iterator semantics for the sequence

### ISSUE THREAD

**Issue by dmitrynogin** [morelinq/MoreLINQ#613]
Consider adding extension like the following:
```csharp
    public static IEnumerable<T> ToIterable<T>(this IEnumerable<T> source)
    {
        var array = source.ToArray();
        var i = 0;
        IEnumerable<T> once()
        {
            while (i < array.Length)
                yield return array[i++];
        }

        return once();
    }
```
that would enable stream reader like functionality:
```csharp
    [TestMethod]
    public void Iterate_Once()
    {
        var x = new[] { 1, 2, 3, 4, 5, 6 }.ToIterable();
        CollectionAssert.AreEqual(new[] { 1, 2 }, x.Take(2).ToArray());
        CollectionAssert.AreEqual(new[] { 3, 4, 5 }, x.Take(3).ToArray());
    }
```

Somehow reminds `Publish` from `System.Reactive`.

**Comment by atifaziz** [comment]
> Somehow reminds `Publish` from `System.Reactive`.

So why not use `Publish` from [System.Interactive](https://www.nuget.org/packages/System.Interactive)?

**Comment by dmitrynogin** [comment]
Way more people are familiar with `IEnumerable` than `IObservable`. I think it could look simpler conceptually.

**Comment by atifaziz** [comment]
But [System.Interactive](https://www.nuget.org/packages/System.Interactive) gives you `Publish` specifically for `IEnumerable<>` so it seems redundant to add it to MoreLINQ.

**Comment by dmitrynogin** [comment]
There it is, but the approach above does not require anything like `IBuffer<T>` disposing. People need to understand a lot about `Publish` implementation details to use it properly.

Also I would expect good programmers to do not add dependency on the functionality they are not familiar with while Rx.NET stays en exotic thing for many. Having this one in MoreLINQ could be an easy kill giving a lot of flexibility for the old well known LINQ.

**Comment by atifaziz** [comment]
> but the approach above does not require anything like `IBuffer<T>` disposing.

That's because what you're proposing eagerly buffers and commits the _entire source_ to memory when the consumer may never need all of it. It also will fail to work with non-terminating sequences. `Publish` requires disposing `IBuffer<T>` because the lifetime of the source enumerator is in control of the user.

I think there's some necessary complexity in `Publish` that's important for the user to understand to make correct use. What you seem to be proposing (which I think is closer to `Share` than `Publish`) is something that would have to be called `ShareList`. It would have to make it very clear that the source is entirely committed to memory over a list and then you could do away with the buffer since managed memory doesn't require disposal. In other words:

```c#
public static IEnumerable<T> ShareList<T>(this IEnumerable<T> source)
{
    var i = 0;
    IEnumerable<T> Share()
    {
        var list = source.ToList();
        while (i < list.Count)
            yield return list[i++];
    }
    return Share();
}    
```

Note that I also deferred materlialization to first iteration.

I would, though, if this is any different or better than `ToList().Share().AsEnumerable()`.

> do not add dependency on the functionality they are not familiar with while Rx.NET stays an exotic thing for many.

Again, this has nothing to do with Rx.NET and I am not an authority on saying whether or not it's exotic for the masses or not.

**Comment by atifaziz** [comment]
/remind me about closing this (if no follow-up) in one month

**Comment by atifaziz** [comment]
Closing due to lack of follow-up.
