### ISSUE TITLE
IntersectBy and other Operators

### ISSUE THREAD

**Issue by b9chris** [morelinq/MoreLINQ#614]
I have my own historical MoreLinq-like library of operators, that I wrote before using MoreLinq. MoreLinq periodically collides with it. I'd like to just contribute my historical library to MoreLinq.

I couldn't find anything on any of the docs pages about how to contribute, so:

1) Are new contributors welcome?
2) Is it the usual, fork, submit pull request, someone reviews?
3) Would these additions be welcome?

Stuff I have:

IntersectBy()
Appears to be in demand, here: https://github.com/morelinq/MoreLINQ/issues/63

ToHashSetIgnoreNulls()
ToHashSetIgnoreDupesAndNulls()
These are what they sound like - just ToHashSet() but less fussy.

ToDictionaryIgnoreDupesAndNulls()

FencePostBefore()
Handles "fence post" situations where you need something to happen at the beginning of a sequence, between, and at the end (like fence posts between fence rails).

I also have this, which lifts older collections up to where MoreLinq can use them:
`IEnumerable<T> ToGeneric<T>(this IEnumerable nonGeneric)`
So, you've got a droopy old plain IEnumerable with no generic type on it. MoreLinq's lights are off. Just call ToGeneric<T>() and it handles all the messy logic of providing an `IEnumerable<T>` so you can use all your MoreLinq goodies on it.

Probably of less interest, but, I'll just mention them: I have some extensions to Dictionary, HashSet, and ICollection, that do things like merge them or RemoveWhere.

**Comment by atifaziz** [comment]
> * Are new contributors welcome?
> * Is it the usual, fork, submit pull request, someone reviews?
> * Would these additions be welcome?

[Yes](https://github.com/morelinq/MoreLINQ/graphs/contributors), yes, and It Depends&trade;. :)

> IEnumerable<T> ToGeneric<T>(this IEnumerable nonGeneric)

Wait, isn't that just [`Cast` from LINQ](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.cast?view=netframework-4.8)?

> I have some extensions to Dictionary, HashSet, and ICollection, that do things like merge them or RemoveWhere.

MoreLINQ is strictly about extending sequences (i.e. `IEnumerable<>`) though I imagine [async streams](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8#asynchronous-streams) may get added to the mix sometime in the near future. Extending any other type is out of scope; that is just to keep to project super focused.
 
- `ToHashSetIgnoreNulls()`
- `ToHashSetIgnoreDupesAndNulls()`
- `ToDictionaryIgnoreDupesAndNulls()`
- `FencePostBefore()`

From just looking at the names, I'd say (and forgive me for jumping to conclusions) these _sound like_ compositions of more primitive operations. Whenever possible, it is preferred to have a sequence operation doing one thing and doing it well; experience shows that it usually leads to more generic and reusable code. There are (very rare) occasions where combinations are rolled into a single operation, like [`PartialSort`](https://morelinq.github.io/3.2/ref/api/html/Overload_MoreLinq_MoreEnumerable_PartialSort.htm) to name one, where the overall operation can benefit from major efficiencies.

> MoreLinq periodically collides with it.

If this is your sole motivation for wanting to contribute to MoreLINQ then I'd say [there's already a way to avoid those conflict](https://github.com/morelinq/MoreLINQ/blob/v3.2.0/README.md#usage).

> IntersectBy()
> Appears to be in demand, here: #63

Just bear in mind that that's been open since 8 years and considering it's not been closed since, I'd say that it's either not in huge demand or it requires someone championing the effort.

Finally, MoreLINQ has been around for a decade. I've seen contributors come and go. In that decade, I'm pretty much the only one still around and keeping the project alive, [maintained (53 releases)](https://github.com/morelinq/MoreLINQ/releases) and current. I might be doing a poor job of that, but given the current state of affairs, most contributions have to pass my gate (and permitting their time, blessings from @fsateler and @leandromoh). That's because I will assume that you won't be around in a year or so to actively maintain your contributions so I will happily discuss an addition and accept and merge a related PR that matches the project's standards and scope, passes reviews and that I'd be willing to maintain going forward. I'm saying this so you walk in with the right set of expectations. If you're here for the long-run then I really look forward to working together.

**Comment by b9chris** [comment]
> > IEnumerable ToGeneric(this IEnumerable nonGeneric)
> 
> Wait, isn't that just [`Cast` from LINQ](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.cast?view=netframework-4.8)?

Oh, I wish. Do you try to use `.Cast()` much? It fails as often as it succeeds, which is why I wrote `.ToGeneric()`. Basically, it's just fussier about converting from one type to another.

> These _sound like_ compositions of more primitive operations. Whenever possible, it is preferred to have a sequence operation doing one thing and doing it well; experience shows that it usually leads to more generic and reusable code. 

That makes sense. I think the method names could be shorter like, ToHashSetGraceful() or something. The core problem is that it's very common to call .ToHashSet() and it explodes on an easily foreseen null or dupe. You can indeed chain it like:

    stuff.Where(x => x != null).Distinct().ToHashSet()

But I created these because it feels like this is how it should've worked in the first place; why would I want null keys or exceptions for dupes in the first place? Those seem like optional behavior I should have to ask for.

FencePostBefore is sort of interesting. I don't know that there is a way to chain other stuff together and accomplish it. Thoughts?

		/// <summary>
		/// Fence post foreach.
		/// 
		/// Runs the before action before calling the loop action each time, except the first time.
		/// </summary>
		/// <typeparam name="T">IEnumerable type</typeparam>
		/// <param name="enumerable">this</param>
		/// <param name="before">A call to make before loopBody is called for all items except the first.</param>
		/// <param name="loopBody">The body you would normally put in a foreach statement.</param>
		public static void FencePostBefore<T>(this IEnumerable<T> enumerable, Action<T> before, Action<T> loopBody)
		{
			var enumerator = enumerable.GetEnumerator();
			if (!enumerator.MoveNext())
				return;

			loopBody(enumerator.Current);

			while (enumerator.MoveNext())
			{
				before(enumerator.Current);
				loopBody(enumerator.Current);
			}
		}


> > IntersectBy()
> > Appears to be in demand, here: #63
> 
> Just bear in mind that that's been open since 8 years and considering it's not been closed since, I'd say that it's either not in huge demand or it requires someone championing the effort.

Well great news, it's written! Effort part's covered.

> That's because I will assume that you won't be around in a year or so to actively maintain your contributions so I will happily discuss an addition and accept and merge a related PR that matches the project's standards and scope, passes reviews and that I'd be willing to maintain going forward.

I think so long as I can sort out how to work with a local build of the Nuget library, built from source while I'm working on it, it'll be easy to keep maintaining it. This library has existed internally for over a decade, and I've been maintaining it that long. I don't assume you'll want everything in it, but MoreLinq has really helped - for example I didn't have to write my own `MaxBy()` - and so hopefully by contributing here, somebody else doesn't have to write their own `IntersectBy()`.

**Comment by b9chris** [comment]
So, are you ready to move forward with these features?

I do see that IntersectBy() was asked for a long time ago, but that's not an indication that interest has gone away - it's an indication it should've been in the library by now.

Here's a more detailed description of why `.Cast<>` fails so often, and why I approach it differently with `.ToGeneric()`
https://stackoverflow.com/a/2819484/176877

**Comment by atifaziz** [comment]
@b9chris [I'm busy with the next release](https://github.com/morelinq/MoreLINQ/milestone/23) so bare with me.

/remind me about reverting to @b9chris in one week

**Comment by atifaziz** [comment]
> Oh, I wish. Do you try to use `.Cast()` much? It fails as often as it succeeds, which is why I wrote `.ToGeneric()`. Basically, it's just fussier about converting from one type to another.
> Here's a more detailed description of why `.Cast<>` fails so often, and why I approach it differently with `.ToGeneric()`
> https://stackoverflow.com/a/2819484/176877

This seems to be confusing _conversion_ with _casting_.

> The core problem is that it's very common to call .ToHashSet() and it explodes on an easily foreseen null or dupe.

`ToHashSet` [can handle nulls](TolerateNullElements) and [duplicates](https://github.com/dotnet/corefx/blob/v3.0.0/src/System.Linq/tests/ToHashSetTests.cs#L54).

> Well great news, it's written! Effort part's covered.

Aye, but that's just your one-time effort. :wink: It doesn't include review, documentation, support and on-going maintenance effort.

> So, are you ready to move forward with these features?

You are free to submit each addition you wish to propose as a separate issue (see #506 as an example). I would hold back submitting a PR until there is an agreement to commit to the new addition. You are welcome to submit a PR in the interest of sharing a working prototype if it helps the discussion so long as you don't assume it'll get merged.

**Comment by atifaziz** [comment]
I am going to close this assuming you will submit your proposals as new and individual issues.

Thanks!
