### ISSUE TITLE
Some test files are missing license header

### ISSUE THREAD

**Issue by Orace** [morelinq/MoreLINQ#671]
Some tests file don't have headers.

We have to choose the license and reference the authors:

To find the authors, we can go through git history for each file.
For the licence, we can take the headers from the tested method.

**Comment by Orace** [comment]
@atifaziz should we do one PR by file?

**Comment by atifaziz** [comment]
I think the test headers needs a complete review with respect to also the copyright notice because we have different copyright holders for different methods depending on original contribution. I addressed this mostly in 57295fff782ddc22d57c3883ed70dd77bd06e338 and 827b630e9786217481b2401e2fdfa694861406e0 but didn't find it a priority for tests assuming that people wouldn't be using that code in other projects. For the tests, it might be a fair compromise to have the copyright notice just read:

    Copyright (c) 2008 MoreLINQ contributors. All rights reserved.

Otherwise you have to dig up the Git history and fix each notice correctly based on original contributors. That's what I did for the main project code and it was a lot of work.

> @atifaziz should we do one PR by file?

This is a single logical issue so it's fine to address it across all files in one PR.

**Comment by atifaziz** [comment]
> > @atifaziz should we do one PR by file?
> 
> This is a single logical issue so it's fine to address it across all files in one PR.

I would add the headers in one PR and fix the copyright notice to a generic one in another as two logically separate changes.

**Comment by Orace** [comment]
>I think the test headers needs a complete review with respect to also the copyright notice because we have different copyright holders for different methods depending on original contribution.

I need clarification here, for _BlaTest_ if no headers are present should we should take:
- the one from _Bla_ 
- the one from Apache License 2.0 (copying.txt)

Anyway I understand that we take the copyright holder from _Bla_ in a first time.

And anyway, you can assign it to me.

**Comment by Orace** [comment]
Turn out missing license was Apache anyway.
