### ISSUE TITLE
Index should be renamed to Number

### ISSUE THREAD

**Issue by Orace** [morelinq/MoreLINQ#688]
See: https://www.lexico.com/en/definition/number

>[Verb, 2] Mark with a number or assign a number to, typically to indicate position in a series.

**Comment by atifaziz** [comment]
Words plucked out of a spoken/written language and used stand-alone generally have ambiguous meaning without some context (provided often by being part of a sentence or phrase) so a [nomenclature](https://en.wikipedia.org/wiki/Nomenclature) usually develops within a domain or field of study that serves as the context. I would therefore argue that _number_ here is not necessarily better than _index_. Yes, an _index_ can seem confusing to a database developer new to C# and MoreLINQ, but a seasoned C# developer (primary audience of this library) generally understands that (or wouldn't be shocked if) it represents a zero-based offset.

Since we are in the domain of LINQ, it's best to reuse names from the domain whenever possible and that's the rational for `Index`. If you look at the description for [`Select<TSource,TResult>(IEnumerable<TSource>, Func<TSource,Int32,TResult>)`](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.select?System_Linq_Enumerable_Select__2_System_Collections_Generic_IEnumerable___0__System_Func___0_System_Int32___1__), it reads:

> Projects each element of a sequence into a new form by incorporating the element's **index**.

Likewise for, [`ElementAt`](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.elementat):

> Returns the element at a specified **index** in a sequence.

The [description for `Index`](https://morelinq.github.io/3.2/ref/api/html/M_MoreLinq_MoreEnumerable_Index__1.htm) reads very clear:

> Returns a sequence of `KeyValuePair<TKey, TValue>` where the key is the **zero-based index** of the value in the source sequence.

I am closing this because it will be introducing a breaking change without adding any value and nobody has complained about the name since it was introduced 7 years ago.

**Comment by Orace** [comment]
This was related to #236

**Comment by atifaziz** [comment]
> This was related to #236

You mean related to [your (following) comment](https://github.com/morelinq/MoreLINQ/pull/236#issuecomment-549186549) in that issue?

> Why not a 0-based `FindIndices`, a plural version of the existing `List<T>.FindIndex` ?
> 
> Or `IndicesWhere` with a predicate ?

**Comment by Orace** [comment]
It's more a reaction to [your comment](https://github.com/morelinq/MoreLINQ/pull/236#issuecomment-296325099) in #236.
Since `Index` can refer to too much concept, the word shouldn't have been used alone.

**Comment by Orace** [comment]
I will also argue that in your examples of use, `index` is an *attribute* of **one** object relatively to a collection. (The index of the element in the collection).
I can't think of an usages of index as a verb in Linq.
