### ISSUE TITLE
MoreEnumerable.From should be removed/renamed

### ISSUE THREAD

**Issue by Orace** [morelinq/MoreLINQ#690]
`MoreEnumerable.From(f1, .., f2)` is an alias for `new[] {f1, .., f2}.Evaluate()`

It doesn't do what users expect (build a sequence of the given elements).

It should be removed or renamed to `Evaluate` (but since evaluate exists, it doesn't provide any new functionality).

**Comment by atifaziz** [comment]
> `MoreEnumerable.From(f1, .., f2)` is an alias for `new[] {f1, .., f2}.Evaluate()`

If you already have delegates/functions then `From` has no value, and as you suggested, it's just better to go with `Evaluate`.

`From` has the benefit that it allows you to _start_ a sequence with terser expressions that are _impossible_ to use with `Evaluate`:

```c#
var xs = MoreEnumerable.From(() => 1, () => 2);
```

You cannot do the same with an array and `Evaluate`:

```c#
var xs = new[] { () => 1, () => 2 }.Evaluate(); // doesn't compile in C#
```

without giving explicitly specifying the type of the array:

```c#
var xs = new[] { new Func<int>(() => 1), () => 2 }.Evaluate();
```

or at least convert one of the lambdas to a specific delegate type:

```c#
var xs = new[] { new Func<int>(() => 1), () => 2 }.Evaluate();
```

But what if you have anonymous types? Then you can't explicitly type the array or the `Func<>` delegates type arguments but `From` has no problem:

```c#
var points =
    MoreEnumerable.From(() => new { X = 1, Y = 2 },
                        () => new { X = 3, Y = 4 });
```

I'll let @fsateler chime in here too.

**Comment by Orace** [comment]
Thanks @atifaziz to enlight the benefits of this function.
For consistency I believe it should have been named `Evaluate`.

**Comment by atifaziz** [comment]
> For consistency I believe it should have been named `Evaluate`.

It's not the same thing; there's a very subtly difference. `Evaluate` does _exactly_ what it's meant to and will only works with function for as far as I can see or imagine. `From` (considering just the name) on the other hand creates a sequence from some _things_ where the only _thing_ we have today is a function. We can _overload_ `From` for other types like some `T` or `Lazy<T>` if that makes sense in the future and we wouldn't have to come up with a new name each time because it's logically yields a sequence across all those types!

I'm going to close this as won't-fix. We have a long history and MoreLINQ has been downloaded over 5 million times to date. We should generally avoid breaking changes (unless there's a serious design flaw) even if a name appears to have been a poor choice in hindsight (which I don't think is the case here).
