### ISSUE TITLE
Should we add GetReverseEnumerable method?

### ISSUE THREAD

**Issue by lindexi** [morelinq/MoreLINQ#747]
Just as this problem: [c# - Possible to iterate backwards through a foreach? - Stack Overflow](https://stackoverflow.com/questions/1211608/possible-to-iterate-backwards-through-a-foreach )

Should we add the GetReverseEnumerable method?

        public static IEnumerable<T> GetReverseEnumerable<T>(this IList<T> list)
        {
            for (var i = list.Count - 1; i >= 0; i--)
            {
                yield return list[i];
            }
        }

**Comment by Crossbow78** [comment]
If you already have a `IList<T> list`, how about `list.ToArray().Reverse()` ?

For anyone wondering why this is not available on an `IEnumerable`, there's simply no way of reversing that without iterating through the whole set first. What if the enumeration never ends?

**Comment by lindexi** [comment]
@Crossbow78 Thank you and the `ToArray` will allocate of more memory

**Comment by atifaziz** [comment]
@lindexi What you're proposing is an extension method for `IList<>` whereas this library is solely concerned with extending `IEnumerable<>` so your proposal best belongs in another library that extends lists.

That said, the implementation is problematic for general use since the `for` loop version, while efficient, could give surprising results if the list is modified during iteration. On the other hand, iterating using the list's iterator will throw if the list is modified during iteration.

For example, the following:

```c#
var xs = Enumerable.Range(1, 5).ToList();
foreach (var x in xs.GetReverseEnumerable())
    xs.Insert(0, x);
```

will give you an `xs` with the following items at the end: 3, 3, 1, 3, 5, 1, 2, 3, 4, 5

Using LINQ's [`Reverse`](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.reverse), however:

```c#
var xs = Enumerable.Range(1, 5).ToList();
foreach (var x in xs.AsEnumerable().Reverse())
    xs.Insert(0, x);
```

will leave `xs` with the content expected through reasoning: 1, 2, 3, 4, 5, 1, 2, 3, 4, 5

Internally, [`Reverse`] buffers the source entirely (no need to call `ToArray` before) before doing the equivalent of your `for` loop (uses indexing).

I am going to close this as out-of-scope.
