### ISSUE TITLE
Add Range.AsEnumerable() extension

### ISSUE THREAD

**Issue by MisinformedDNA** [morelinq/MoreLINQ#762]
Currently, we can create a sequence using a static method:

```csharp
MoreEnumerable.Sequence(start, stop);
```

However, it would be nice if we could instead start with a C# construct like:

```csharp
(start..stop).AsEnumerable();
```

I propose adding:

```csharp
public static IEnumberable<int> AsEnumerable(this Range range);
```

**Comment by Aaron-Lathrop** [comment]
Something like this?

![image](https://user-images.githubusercontent.com/39559277/95016081-f635e200-060d-11eb-8d3b-d9da8c950dd2.png)

**Comment by atifaziz** [comment]
This would belong in a more general library of extension methods or even one specific for `Range`. Unfortunately, it's out of scope for this library since MoreLINQ doesn't provide extension methods for other types than sequences (`IEnumerable<>`). It would also cause some confusion with [`MoreEnumerable.Sequence`](http://morelinq.github.io/3.3/ref/api/html/Overload_MoreLinq_MoreEnumerable_Sequence.htm) since, unlike `Range`, its _stop_ argument is inclusive. It could also lead to subtle bugs if, for example, (starting with C# 9) some provided an iteration extension for `Range` so it could be used in `foreach` loops like so:

```c#
foreach (var x in 1..10)
    Console.WriteLine(x);

static class RangeExtensions
{
    public static IEnumerator<int> GetEnumerator(this Range range)
    {
        var max = (long)int.MaxValue + 1;
        long Normalize(Index i) => i.IsFromEnd ? max - i.Value : i.Value;
        var (start, end) = (Normalize(range.Start), Normalize(range.End));
        for (var i = start; i < end; i++)
            yield return checked((int)i);
    }
}
```

The above will print numbers from 1 to 9. It won't be simply interchangeable with `MoreEnumerable.Sequence` or an `AsEnumerable` extension method for `Range` that includes the end.

Putting all that aside, [`Range`](https://docs.microsoft.com/en-us/dotnet/api/system.range?view=net-5.0) isn't really designed to be used for representing a range of numbers but rather a slice defined by _indicies_. Both its `Start` and `End` are typed as [`Index`](https://docs.microsoft.com/en-us/dotnet/api/system.index?view=net-5.0) so using it otherwise would just mislead or bring about artificial limitations. For example, you can't really use it to do something like `MoreEnumerable.Sequence(-10, 10)` since `Index` cannot be initialized with a negative number.

**Comment by atifaziz** [comment]
You might be interested in checking out #748 where a more appropriate use of `Range` as a one-stop shortcut to many extensions (or combinations thereof) is being proposed.
