### ISSUE TITLE
Excluding a single value?

### ISSUE THREAD

**Issue by DaveInCaz** [morelinq/MoreLINQ#768]
I've looked through MoreLINQ but didn't see any method that would simplify exclusion of a single value. (Maybe I missed something, I'm new to it...)

For example, I would like to be able to do something like this:

`foreach(var x in Vehicles.Exclude("car")) { ... } `

but neither LINQ nor MoreLINQ seems to offer a direct way to do this?

Obviously you could do `Vehicles.Where(v => v!="car")`, this is just more verbose.

**Comment by atifaziz** [comment]
LINQ and MoreLINQ are not about reducing verbosity of code at every level. What you're asking for is a one-liner:

```c#
static IEnumerable<T> Exclude<T>(this IEnumerable<T> source, T value) =>
    source.Where(x => !EqualityComparer<T>.Default.Equals(x, value));
```

It doesn't really do anything new or interesting algorithmically-speaking, which is why I reckon you won't find it in LINQ or here. If you find such tiny helpers make your code shorter and more readable then it's best to build them into your project or publish as a separate library that build on top of LINQ and with the goal of helping to be brief. For example, I have one such [library/project to help deal exclusively with `KeyValuePair<,>` and sequences of such values](https://github.com/atifaziz/KeyValuePairs).

I am going to close this assuming your question is answered, but feel free to re-open if I've misunderstood you.

**Comment by DaveInCaz** [comment]
@atifaziz thanks for the reply & explanation. I agree the main point would be for brevity (with the main goal of making things as understandable as possible to other coders, especially sometimes less experienced ones).

But that's not to say that this should be the goal of MoreLINQ! :)

Thanks for pointing out the other library, I'll take a look.

Dave
