### ISSUE TITLE
Batch on ConcurrentDictionary

### ISSUE THREAD

**Issue by mattheww-freshview** [morelinq/MoreLINQ#794]
`Batch` (like many LINQ operators) doesn't play so well with `ConcurrentDictionary`. Presumably this is due to https://github.com/morelinq/MoreLINQ/blob/master/MoreLinq/Batch.cs#L99 .

Repro:

```
using System;
using System.Collections.Concurrent;
using System.Linq;
using System.Threading.Tasks;
using MoreLinq;

namespace TestingExceptionHandling
{
	public class Program
	{
		public static void Main()
		{


			var dictionary = new ConcurrentDictionary<int, int>();
			Task.Run(() =>
			{
				var random = new Random();

				do
				{

					if (random.Next(1000) < 30)
					{
						dictionary.Clear();
					}
					else
					{
						dictionary[random.Next(10000)] = 5;
					}
				} while (true);
			});

			Task.Run(() =>
			{
				do
				{
					try
					{
						var batches = dictionary.Batch(1000).ToList();
					}
					catch (Exception e)
					{
						Console.WriteLine(e);
					}
				} while (true);
			});

			Console.ReadLine();
		}
	}
}

```

I can work around it by using
```
var batches = dictionary.Select(z => z).Batch(1000).ToList();
```

instead. Are there other alternatives?

**Comment by atifaziz** [comment]
> Presumably this is due to https://github.com/morelinq/MoreLINQ/blob/master/MoreLinq/Batch.cs#L99 .

It's more to do with the fact that the `Count` _and_ `CopyTo` operations on the source collection (the concurrent dictionary), are not atomic or collectively provide a snapshot view of the collection:

https://github.com/morelinq/MoreLINQ/blob/ab9e5617139345936eab383828babafe00d4eb30/MoreLinq/Batch.cs#L98-L99

The dictionary could change between the time when the count is queried and when the elements are copied. When you use `Select`, it uses the collection's own iterator, which is implemented to provide a consistent view through the entire iteration. Not only that, it causes `Batch` to take a different path too, since it sees the source, having changed its identity, as an iterable sequence instead of a materialized collection (that is, as an instance of `ICollection<KeyValuePair<,>>`); that it iterates it to build up the batches to serve.

> Are there other alternatives?

I am afraid, I don't see any good alternative because the current abstractions, like `ICollection<>` and family, are not designed for concurrency. The non-generic versions had an [`ICollection.SyncRoot`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.icollection.syncroot?view=net-5.0), but which isn't always supported. [`ConcurrentDictionary<,>` certainly doesn't](https://github.com/dotnet/runtime/blob/8a52f1e948b6f22f418817ec1068f07b8dae2aa5/src/libraries/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentDictionary.cs#L1861-L1866).

**Comment by mattheww-freshview** [comment]
Yes, sorry I should have been clearer - I understand _why_ the issue occurs.

**Comment by atifaziz** [comment]
@mattheww-freshview Consider it as notes to my future self and others. 😉
