### ISSUE TITLE
Review `ToArrayByIndex` Nullability

### ISSUE THREAD

**Issue by viceroypenguin** [morelinq/MoreLINQ#962]
`ToArrayByIndex` should return `TResult?` and `T?` instead of `TResult` and `T` respectively. This is because the operator does not guarantee that every index in the return array has been set to a value.

Related to #803

**Comment by atifaziz** [comment]
I would say the current signatures are by-design and I'm afraid there might be no good answer here due to [arrays being one of the holes in nullable reference analysis](https://learn.microsoft.com/en-us/dotnet/csharp/nullable-references#known-pitfalls):

> Arrays and structs that contain reference types are known pitfalls in nullable references and the static analysis that determines null safety. In both situations, a non-nullable reference may be initialized to `null`, without generating warnings.

Whether the resulting array should have nullable elements really depends on the source leading to a dense or a sparse population of the resulting array. The developer is really in the best position to decide. This is more so true for [the](https://morelinq.github.io/3.3/ref/api/html/M_MoreLinq_MoreEnumerable_ToArrayByIndex__1.htm) [overloads](https://morelinq.github.io/3.3/ref/api/html/M_MoreLinq_MoreEnumerable_ToArrayByIndex__1_1.htm) that have a single generic parameter `T` than those that allow the resulting type, `TResult`, to vary because you can always project to a `TResult?`.

There's even a bigger problem with _forcing_ `TResult?` in the signature, which is, you don't leave the developer the choice to ever be able to say elements are of type `TResult` (even through the projection) if the array is known to be densely populated (requiring `!` to be used downstream). It also gets stranger when `T`/`TResult` is a value type because `T?`/`TResult?` then just becomes `T`/`TResult` and you won't get nulls but defaults for holes in the array (zeros if it's `int[]`). The semantics could then get confusing.

The current nullable annotations seem to provide a good balance unless something's being overlooked. Perhaps the right course of action here is to document the potential for mistyping when the population is sparse?

**Comment by atifaziz** [comment]
Since there's been no further comment on this, I'll assume it's not an issue any longer.
