### ISSUE TITLE
Remove `Concat` that's been obsolete since 3.0

### ISSUE THREAD

**Issue by atifaziz** [morelinq/MoreLINQ#993]
The `Concat` method was superseded by `Append` (see #496) and `Concat` has been marked obsolete since version 3.0. It's time to remove it with the next major version.

**Comment by pflajszer** [comment]
Hey [atifaziz](https://github.com/atifaziz). I can see that `Concat` already calls `Append` internally. Is is just a matter of removing that single method in `Append.cs`?

Happy to take that one if you're ok with that?
I'm just getting comfortable contributing to OS projects, so that looks like a reasonable one to start with.  

Thanks

**Comment by pflajszer** [comment]
Thanks a lot @atifaziz . Here's the PR: [link](https://github.com/morelinq/MoreLINQ/pull/1002). Please let me know if that looks OK!
